(()=>{'use strict';
const personal=new Set('jma_favorites jma_found jma_hunt jma_hunt_meta jma_saved_builds jma_build_draft jma_routes jma_route_draft jma_plans jma_submissions jma_community_posts jma_custom_markers jma_exchange_posts jma_secret_notes jma_patch_notes jma_invention_slots jma_gallery jma_profile_appearance jma_tech_seen jma_achievements jma_invention_saved'.split(' '));
const owner=()=>globalThis.JMA_AUTH?.getAccount?.()?.id||'guest';
function migrate(id){if(id==='guest'||localStorage.getItem(`oha:legacy-migrated:${id}`))return;const first=localStorage.getItem('oha:legacy-owner');if(!first||first===id){localStorage.setItem('oha:legacy-owner',id);for(const k of personal){const old=localStorage.getItem(k),key=`oha:${id}:${k}`;if(old!==null&&localStorage.getItem(key)===null)localStorage.setItem(key,old)}}localStorage.setItem(`oha:legacy-migrated:${id}`,'1')}
function key(k){const id=owner();migrate(id);return personal.has(k)?`oha:${id}:${k}`:k}
function read(k,f=null){try{const s=localStorage.getItem(key(k));return s===null?f:JSON.parse(s)}catch{return f}}
function write(k,v){try{localStorage.setItem(key(k),JSON.stringify(v))}catch{throw new Error('Browser-Speicher voll oder nicht verfügbar. Daten wurden nicht gespeichert.')}}
function replace(values){const previous=new Map();try{for(const [k,v]of Object.entries(values)){const target=key(k);previous.set(target,localStorage.getItem(target));localStorage.setItem(target,JSON.stringify(v))}}catch(error){for(const [k,v]of previous){try{v===null?localStorage.removeItem(k):localStorage.setItem(k,v)}catch{}}throw new Error('Import konnte nicht gespeichert werden; vorherige Daten bleiben erhalten.',{cause:error})}}
globalThis.JMA_STORE={read,write,key,replace,remove:k=>localStorage.removeItem(key(k)),personal:[...personal]};
let dbPromise;function db(){return dbPromise||=(new Promise((resolve,reject)=>{const r=indexedDB.open('once-human-media',1);r.onupgradeneeded=()=>r.result.createObjectStore('images');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}))}
async function request(mode,fn){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('images',mode),r=fn(tx.objectStore('images'));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function save(file){if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw new Error('Bitte PNG, JPG oder WebP bis 10 MB wählen.');const image=await createImageBitmap(file);const c=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(image.width,image.height));c.width=Math.round(image.width*scale);c.height=Math.round(image.height*scale);c.getContext('2d').drawImage(image,0,0,c.width,c.height);image.close();const blob=await new Promise(r=>c.toBlob(r,'image/webp',.86));if(!blob)throw new Error('Bild konnte nicht verarbeitet werden.');const id=`upload-${crypto.randomUUID()}`;await request('readwrite',s=>s.put(blob,`${owner()}:${id}`));return id}
async function hydrate(root=document){await Promise.all([...root.querySelectorAll('[data-media-id]')].map(async img=>{try{const b=await request('readonly',s=>s.get(`${owner()}:${img.dataset.mediaId}`));if(!b)return;const url=URL.createObjectURL(b);img.onload=img.onerror=()=>URL.revokeObjectURL(url);img.src=url}catch{img.alt='Lokales Bild nicht verfügbar'}}))}
globalThis.JMA_MEDIA={save,hydrate,remove:id=>request('readwrite',s=>s.delete(`${owner()}:${id}`))};
})();
