(()=>{
'use strict';
const AD=()=>globalThis.ARCHIVE_DATA||{};
const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const read=(k,f=null)=>{try{const v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const arr=(k)=>{const v=read(k,[]);return Array.isArray(v)?v:[]};
const set=(k)=>new Set(arr(k));
const putSet=(k,s)=>write(k,[...s]);
const catalog=()=>Array.isArray(globalThis.CATALOG_DATA?.entries)?globalThis.CATALOG_DATA.entries:[];
const account=()=>read('jma_session',null)||read('jma_account',null);
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const fmt=d=>{try{return new Date(d).toLocaleDateString('de-DE',{day:'2-digit',month:'short',year:'numeric'})}catch{return d||'—'}};
const go=id=>{location.hash=`#/${id}`};
const refresh=()=>globalThis.JMA_RENDER?.();
const inputRefresh=(key,value,selector,delay=260)=>{write(key,value);clearTimeout(globalThis.__rfInputRefresh);globalThis.__rfInputRefresh=setTimeout(()=>{refresh();setTimeout(()=>{const el=qs(selector);if(el){el.focus();const n=el.value?.length||0;try{el.setSelectionRange(n,n)}catch{}}},0)},delay)};
const toast=msg=>{const t=qs('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(globalThis.__rfToast);globalThis.__rfToast=setTimeout(()=>t.classList.remove('show'),2200)};
const hero=(k,t,p,side='')=>`<header class="rf-hero"><div><div class="section-kicker">${esc(k)}</div><h1>${esc(t)}</h1><p>${esc(p)}</p></div>${side?`<aside>${side}</aside>`:''}</header>`;
const metrics=items=>`<div class="rf-metrics">${items.map(([n,l])=>`<span><b>${esc(n)}</b><small>${esc(l)}</small></span>`).join('')}</div>`;
const empty=t=>`<div class="rf-empty"><b>${esc(t)}</b><span>Hier gibt es im aktuellen lokalen Stand noch nichts anzuzeigen.</span></div>`;
const btnLink=(route,label,cls='ghost-btn')=>`<button class="${cls}" type="button" data-rf-go="${esc(route)}">${esc(label)}</button>`;
const on=(sel,ev,fn)=>qs(sel)?.addEventListener(ev,fn);
const navBinds=()=>qsa('[data-rf-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.rfGo)));

function renderDashboard(){
 const a=account(), fav=set('jma_favorites'), hunt=set('jma_hunt'), builds=arr('jma_saved_builds'), routes=arr('jma_routes'), plans=arr('jma_plans');
 return `<section class="rf-page dashboard-page">${hero('KOMMANDOZENTRALE','DEIN ARCHIV',a?`Willkommen zurück, ${a.name||a.email}. Deine lokalen Werkzeuge laufen in einem gemeinsamen Arbeitsbereich.`:'Persönlicher Überblick über Sammlung, Jagdliste, Builds und Einsätze. Für Kontodaten kannst du dich über die bestehende Anmeldung registrieren.')}
 ${metrics([[fav.size,'Favoriten'],[hunt.size,'Jagdziel(e)'],[builds.length,'gespeicherte Builds'],[routes.length,'Routen'],[plans.length,'Einsatzpläne']])}
 <div class="rf-command-grid"><article class="rf-feature"><span>◎</span><small>NÄCHSTER SCHRITT</small><h2>${hunt.size?'Jagdliste abarbeiten':'Erstes Jagdziel setzen'}</h2><p>${hunt.size?'Öffne deine markierten Katalogziele und pflege Priorität bzw. Status.':'Übernimm aus der Datenbank einen Eintrag direkt in deine Jagdliste.'}</p>${btnLink(hunt.size?'hunt':'database',hunt.size?'JAGDLISTE ÖFFNEN':'DATENBANK ÖFFNEN','cyan-btn compact')}</article>
 <article class="rf-panel"><div class="rf-panel-head"><b>WERKZEUGE</b><small>dein Arbeitsraum</small></div><div class="rf-action-stack">${btnLink('map','⌖ INTERAKTIVE KARTE')}${btnLink('builds','⚒ BUILD-WERKSTATT')}${btnLink('planner','◷ EINSATZPLANER')}${btnLink('collection','★ MEINE SAMMLUNG')}</div></article>
 <article class="rf-panel wide"><div class="rf-panel-head"><b>ARCHIVSTATUS</b><small>28 feste Routen</small></div><div class="rf-progress-row"><span>Startseite</span><i><em style="width:100%"></em></i><b>aktiv</b></div><div class="rf-progress-row"><span>Datenbank</span><i><em style="width:100%"></em></i><b>aktiv</b></div><div class="rf-progress-row"><span>Persönlicher Zustand</span><i><em style="width:${a?100:55}%"></em></i><b>${a?'verbunden':'lokal'}</b></div></article></div></section>`;
}

function renderNews(){
 const rows=AD().seed?.news||[]; const cat=read('jma_news_filter','all'); const filtered=cat==='all'?rows:rows.filter(x=>x.category===cat); const cats=[...new Set(rows.map(x=>x.category))];
 const feature=filtered.find(x=>x.featured)||filtered[0];
 return `<section class="rf-page news-page">${hero('ARCHIV // SIGNAL','NEUIGKEITEN','Projektmeldungen und dokumentierte Archiv-Updates aus dem erhaltenen Projektstand.')}
 <div class="rf-tabs"><button class="${cat==='all'?'active':''}" data-news-cat="all">ALLE</button>${cats.map(c=>`<button class="${cat===c?'active':''}" data-news-cat="${esc(c)}">${esc(c.toUpperCase())}</button>`).join('')}</div>
 ${feature?`<article class="rf-news-feature"><div class="visual"></div><div><small>${esc(feature.category)} · ${fmt(feature.date)}</small><h2>${esc(feature.title)}</h2><p>${esc(feature.summary)}</p><button class="cyan-btn compact" type="button" data-news-open="${esc(feature.id)}">MELDUNG LESEN →</button></div></article>`:''}
 <div class="rf-news-list">${filtered.map(n=>`<article><small>${fmt(n.date)} · ${esc(n.category)}</small><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p><button type="button" data-news-open="${esc(n.id)}">DETAILS</button><div class="rf-news-body" data-news-body="${esc(n.id)}" hidden>${esc(n.body)}</div></article>`).join('')}</div></section>`;
}
function bindNews(){navBinds();qsa('[data-news-cat]').forEach(b=>b.onclick=()=>{write('jma_news_filter',b.dataset.newsCat);refresh()});qsa('[data-news-open]').forEach(b=>b.onclick=()=>{const x=qs(`[data-news-body="${CSS.escape(b.dataset.newsOpen)}"]`);if(x){x.hidden=!x.hidden;b.textContent=x.hidden?'DETAILS':'SCHLIESSEN'}})}

const mapCustom=()=>arr('jma_custom_markers');
const allMarkers=()=>[...(AD().map?.markers||[]),...mapCustom().map(x=>({...x,custom:true}))];
function mapSelected(){return read('jma_map_selected','')}
function markerDetail(m){if(!m)return `<div class="rf-map-detail-empty"><span>⌖</span><b>MARKER AUSWÄHLEN</b><p>Wähle einen sichtbaren Marker, um Quelle, Szenario und Notiz anzuzeigen.</p></div>`;return `<div class="section-kicker">MARKERDETAIL</div><h2>${esc(m.name)}</h2><div class="rf-kv"><span><small>SZENARIO</small><b>${esc((AD().map?.scenarios||[]).find(s=>s.id===m.scenario)?.name||m.scenario)}</b></span><span><small>KATEGORIE</small><b>${esc(m.category||'Marker')}</b></span><span><small>SPIELKOORDINATEN</small><b>${m.gameX||m.gameY?`X ${esc(m.gameX||'—')} / Y ${esc(m.gameY||'—')}`:'noch nicht hinterlegt'}</b></span><span><small>PRÜFSTATUS</small><b>${esc(m.verified||'lokal')}</b></span></div><p>${esc(m.note||'')}</p><div class="rf-action-stack"><button class="cyan-btn compact" type="button" data-map-route-add="${esc(m.id)}">＋ ZUR ROUTE</button>${m.custom?`<button class="ghost-btn" type="button" data-map-delete="${esc(m.id)}">LOKALEN MARKER LÖSCHEN</button>`:''}</div>`}
function renderMap(){
 const scenarios=AD().map?.scenarios||[], scenario=read('jma_map_scenario','way-of-winter'), q=read('jma_map_q',''), cat=read('jma_map_cat','all');
 const candidates=allMarkers().filter(m=>m.scenario===scenario); const cats=[...new Set(candidates.map(x=>x.category).filter(Boolean))];
 const markers=candidates.filter(m=>(cat==='all'||m.category===cat)&&(!q||`${m.name} ${m.category} ${m.note} ${m.location}`.toLowerCase().includes(q.toLowerCase()))); const selected=allMarkers().find(x=>x.id===mapSelected());
 const view=read('jma_map_view',{zoom:1,x:0,y:0});
 return `<section class="rf-page map-page">${hero('KARTENZENTRALE // INTERN','INTERAKTIVE KARTE','Szenarioebenen, bestätigte Marker, lokale Ergänzungen und gespeicherte Routen aus dem vorhandenen Projektstand.',metrics([[scenarios.length,'Szenarien'],[allMarkers().length,'Marker gesamt'],[markers.length,'sichtbar']]))}
 <div class="rf-map-toolbar"><label>SZENARIO<select id="mapScenario">${scenarios.map(s=>`<option value="${esc(s.id)}" ${s.id===scenario?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>MARKER SUCHEN<input id="mapSearch" value="${esc(q)}" placeholder="Silo, Kategorie, Notiz …"></label><label>KATEGORIE<select id="mapCategory"><option value="all">Alle</option>${cats.map(c=>`<option ${c===cat?'selected':''}>${esc(c)}</option>`).join('')}</select></label><div class="rf-map-zoom"><button id="mapZoomOut" type="button">−</button><b>${Math.round((view.zoom||1)*100)}%</b><button id="mapZoomIn" type="button">＋</button><button id="mapResetView" type="button">RESET</button></div></div>
 <div class="rf-map-layout"><aside class="rf-map-layers"><small>EBENEN</small>${scenarios.map(s=>`<button class="${s.id===scenario?'active':''}" data-map-scenario="${esc(s.id)}"><b>${esc(s.name)}</b><span>${esc(s.note||'')}</span><em>${allMarkers().filter(m=>m.scenario===s.id).length}</em></button>`).join('')}<div class="rf-map-draft"><small>ROUTENENTWURF</small>${arr('jma_route_draft').map(id=>{const m=allMarkers().find(x=>x.id===id);return m?`<span>${esc(m.name)}</span>`:''}).join('')||'<p>Noch keine Marker gewählt.</p>'}${btnLink('routes','ROUTEN VERWALTEN')}</div></aside>
 <div class="rf-map-board" id="mapBoard"><div class="rf-map-plane" id="mapPlane" style="transform:translate(${Number(view.x)||0}px,${Number(view.y)||0}px) scale(${Number(view.zoom)||1})"><div class="rf-map-grid"></div><div class="rf-map-region-label">${esc(scenarios.find(s=>s.id===scenario)?.name||scenario)}</div>${markers.map(m=>`<button class="rf-map-marker ${m.id===mapSelected()?'active':''} ${m.custom?'custom':''}" type="button" title="${esc(m.name)}" data-map-marker="${esc(m.id)}" style="left:${Number(m.mapX)||50}%;top:${Number(m.mapY)||50}%"><span>⌖</span></button>`).join('')}</div><div class="rf-map-help">Ziehen = verschieben · Mausrad / ± = zoomen</div></div>
 <aside class="rf-map-detail" id="mapDetail">${markerDetail(selected)}<div class="rf-map-editor"><small>LOKALEN MARKER ERGÄNZEN</small><form id="mapMarkerForm"><input name="name" placeholder="Markername" required><div><input name="x" type="number" min="0" max="100" value="50" required><input name="y" type="number" min="0" max="100" value="50" required></div><input name="category" placeholder="Kategorie" value="Eigener Marker"><textarea name="note" placeholder="Notiz / Fundweg"></textarea><button class="ghost-btn" type="submit">MARKER SPEICHERN</button></form></div></aside></div></section>`;
}
function bindMap(){navBinds();const setSc=v=>{write('jma_map_scenario',v);write('jma_map_selected','');refresh()};on('#mapScenario','change',e=>setSc(e.target.value));qsa('[data-map-scenario]').forEach(b=>b.onclick=()=>setSc(b.dataset.mapScenario));on('#mapSearch','input',e=>inputRefresh('jma_map_q',e.target.value,'#mapSearch'));on('#mapCategory','change',e=>{write('jma_map_cat',e.target.value);refresh()});qsa('[data-map-marker]').forEach(b=>b.onclick=e=>{e.stopPropagation();write('jma_map_selected',b.dataset.mapMarker);refresh()});on('#mapMarkerForm','submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),scenario=read('jma_map_scenario','way-of-winter'),rows=mapCustom();const m={id:uid('custom-marker'),scenario,name:String(fd.get('name')).trim(),category:String(fd.get('category')||'Eigener Marker').trim(),mapX:+fd.get('x'),mapY:+fd.get('y'),location:'Lokale Ergänzung',note:String(fd.get('note')||'').trim(),verified:'lokal',catalogIds:[]};rows.push(m);write('jma_custom_markers',rows);write('jma_map_selected',m.id);toast('Lokaler Marker gespeichert.');refresh()});qsa('[data-map-delete]').forEach(b=>b.onclick=()=>{write('jma_custom_markers',mapCustom().filter(x=>x.id!==b.dataset.mapDelete));write('jma_map_selected','');toast('Lokaler Marker gelöscht.');refresh()});qsa('[data-map-route-add]').forEach(b=>b.onclick=()=>{const r=arr('jma_route_draft');if(!r.includes(b.dataset.mapRouteAdd))r.push(b.dataset.mapRouteAdd);write('jma_route_draft',r);toast('Marker zum Routenentwurf hinzugefügt.');refresh()});
 const board=qs('#mapBoard'),plane=qs('#mapPlane');if(!board||!plane)return;let v=read('jma_map_view',{zoom:1,x:0,y:0}),drag=null;const apply=()=>{plane.style.transform=`translate(${v.x}px,${v.y}px) scale(${v.zoom})`;write('jma_map_view',v)};const zoom=d=>{v.zoom=Math.max(.65,Math.min(2.2,(v.zoom||1)+d));apply();const b=qs('.rf-map-zoom b');if(b)b.textContent=`${Math.round(v.zoom*100)}%`};on('#mapZoomIn','click',()=>zoom(.15));on('#mapZoomOut','click',()=>zoom(-.15));on('#mapResetView','click',()=>{v={zoom:1,x:0,y:0};apply();refresh()});board.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?.1:-.1)},{passive:false});board.addEventListener('pointerdown',e=>{if(e.target.closest('.rf-map-marker'))return;drag={x:e.clientX,y:e.clientY,bx:v.x||0,by:v.y||0};board.setPointerCapture(e.pointerId)});board.addEventListener('pointermove',e=>{if(!drag)return;v.x=drag.bx+(e.clientX-drag.x);v.y=drag.by+(e.clientY-drag.y);apply()});board.addEventListener('pointerup',()=>drag=null)}

function renderHunt(){const ids=[...set('jma_hunt')],meta=read('jma_hunt_meta',{});const rows=ids.map(id=>catalog().find(x=>x.id===id)).filter(Boolean);return `<section class="rf-page hunt-page">${hero('PERSÖNLICH // ZIELE','JAGDLISTE','Katalogziele priorisieren, als erledigt markieren oder direkt zur Datenbank zurückspringen.',metrics([[rows.length,'aktive Einträge'],[rows.filter(x=>meta[x.id]?.done).length,'erledigt']]))}<div class="rf-hunt-list">${rows.map(x=>`<article class="${meta[x.id]?.done?'done':''}"><div><small>${esc(x.kind||x.category)}</small><h3>${esc(x.name_de)}</h3><p>${esc(x.acquisition||x.description||'')}</p></div><label>PRIORITÄT<select data-hunt-priority="${esc(x.id)}"><option ${meta[x.id]?.priority==='Hoch'?'selected':''}>Hoch</option><option ${!meta[x.id]?.priority||meta[x.id]?.priority==='Normal'?'selected':''}>Normal</option><option ${meta[x.id]?.priority==='Niedrig'?'selected':''}>Niedrig</option></select></label><div class="actions"><button type="button" data-hunt-done="${esc(x.id)}">${meta[x.id]?.done?'↺ ÖFFNEN':'✓ ERLEDIGT'}</button><button type="button" data-hunt-remove="${esc(x.id)}">ENTFERNEN</button></div></article>`).join('')||empty('Keine Jagdziele')}<div class="rf-inline-cta">${btnLink('database','＋ AUS DATENBANK HINZUFÜGEN','cyan-btn compact')}</div></div></section>`}
function bindHunt(){navBinds();qsa('[data-hunt-priority]').forEach(s=>s.onchange=()=>{const m=read('jma_hunt_meta',{});m[s.dataset.huntPriority]={...(m[s.dataset.huntPriority]||{}),priority:s.value};write('jma_hunt_meta',m);toast('Priorität gespeichert.')});qsa('[data-hunt-done]').forEach(b=>b.onclick=()=>{const m=read('jma_hunt_meta',{}),id=b.dataset.huntDone;m[id]={...(m[id]||{}),done:!m[id]?.done};write('jma_hunt_meta',m);refresh()});qsa('[data-hunt-remove]').forEach(b=>b.onclick=()=>{const s=set('jma_hunt');s.delete(b.dataset.huntRemove);putSet('jma_hunt',s);refresh()})}

function renderRoutes(){const saved=arr('jma_routes'),draft=arr('jma_route_draft');return `<section class="rf-page routes-page">${hero('KARTE // PLANUNG','FARMROUTEN','Marker zu eigenen Routen verbinden. Gespeicherte Routen bleiben lokal im Browser und öffnen ihre Stationen wieder auf der Karte.')}
 <div class="rf-routes-grid"><section class="rf-panel"><div class="rf-panel-head"><b>AKTUELLER ENTWURF</b><small>${draft.length} Stationen</small></div><div class="rf-route-steps">${draft.map((id,i)=>{const m=allMarkers().find(x=>x.id===id);return m?`<div><b>${i+1}</b><span>${esc(m.name)}</span><button data-route-step-remove="${esc(id)}">×</button></div>`:''}).join('')||empty('Entwurf leer')}</div><form id="routeSaveForm"><input name="name" placeholder="Routenname" required><button class="cyan-btn compact" type="submit" ${draft.length?'':'disabled'}>ROUTE SPEICHERN</button></form>${btnLink('map','⌖ MARKER AUF KARTE WÄHLEN')}</section>
 <section class="rf-panel"><div class="rf-panel-head"><b>GESPEICHERTE ROUTEN</b><small>${saved.length}</small></div><div class="rf-saved-list">${saved.map(r=>`<article><div><small>${fmt(r.created)}</small><h3>${esc(r.name)}</h3><p>${r.markers.length} Stationen</p></div><div><button data-route-open="${esc(r.id)}">ÖFFNEN</button><button data-route-delete="${esc(r.id)}">LÖSCHEN</button></div></article>`).join('')||empty('Noch keine Route gespeichert')}</div></section></div></section>`}
function bindRoutes(){navBinds();qsa('[data-route-step-remove]').forEach(b=>b.onclick=()=>{write('jma_route_draft',arr('jma_route_draft').filter(x=>x!==b.dataset.routeStepRemove));refresh()});on('#routeSaveForm','submit',e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name').trim(),draft=arr('jma_route_draft');if(!name||!draft.length)return;const rows=arr('jma_routes');rows.unshift({id:uid('route'),name,markers:draft,created:new Date().toISOString()});write('jma_routes',rows);write('jma_route_draft',[]);toast('Route gespeichert.');refresh()});qsa('[data-route-delete]').forEach(b=>b.onclick=()=>{write('jma_routes',arr('jma_routes').filter(x=>x.id!==b.dataset.routeDelete));refresh()});qsa('[data-route-open]').forEach(b=>b.onclick=()=>{const r=arr('jma_routes').find(x=>x.id===b.dataset.routeOpen);if(!r)return;write('jma_route_draft',r.markers);if(r.markers[0])write('jma_map_selected',r.markers[0]);go('map')})}

function renderPlanner(){const plans=arr('jma_plans'),hunts=[...set('jma_hunt')].map(id=>catalog().find(x=>x.id===id)).filter(Boolean),builds=arr('jma_saved_builds'),routes=arr('jma_routes');return `<section class="rf-page planner-page">${hero('SESSION // PLANUNG','EINSATZPLANER','Eine Spielsitzung aus Jagdzielen, Build und Kartenroute zusammensetzen und lokal speichern.')}
 <div class="rf-planner-layout"><form class="rf-panel rf-plan-form" id="planForm"><div class="rf-panel-head"><b>NEUER EINSATZ</b><small>lokaler Plan</small></div><label>TITEL<input name="title" required placeholder="z. B. Winter-Silos"></label><div class="rf-form-pair"><label>DATUM<input type="date" name="date"></label><label>FOKUS<select name="focus"><option>Farm</option><option>Boss</option><option>Erkundung</option><option>Tech</option><option>Community</option></select></label></div><label>JAGDZIEL<select name="hunt"><option value="">Keins</option>${hunts.map(x=>`<option value="${esc(x.id)}">${esc(x.name_de)}</option>`).join('')}</select></label><label>BUILD<select name="build"><option value="">Kein Build</option>${builds.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select></label><label>ROUTE<select name="route"><option value="">Keine Route</option>${routes.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select></label><label>NOTIZ<textarea name="note" placeholder="Materialien, Gruppe, Reihenfolge …"></textarea></label><button class="cyan-btn compact" type="submit">EINSATZ SPEICHERN</button></form>
 <section class="rf-panel"><div class="rf-panel-head"><b>GEPLANTE EINSÄTZE</b><small>${plans.length}</small></div><div class="rf-plan-list">${plans.map(p=>`<article><div><small>${p.date?fmt(p.date):'ohne Datum'} · ${esc(p.focus)}</small><h3>${esc(p.title)}</h3><p>${esc(p.note||'')}</p><div class="rf-chips">${p.hunt?'<span>◎ Jagdziel</span>':''}${p.build?'<span>⚒ Build</span>':''}${p.route?'<span>⌖ Route</span>':''}</div></div><button data-plan-delete="${esc(p.id)}">×</button></article>`).join('')||empty('Noch kein Einsatz geplant')}</div></section></div></section>`}
function bindPlanner(){navBinds();on('#planForm','submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),rows=arr('jma_plans');rows.unshift({id:uid('plan'),title:String(fd.get('title')).trim(),date:fd.get('date'),focus:fd.get('focus'),hunt:fd.get('hunt'),build:fd.get('build'),route:fd.get('route'),note:String(fd.get('note')||'').trim(),created:new Date().toISOString()});write('jma_plans',rows);toast('Einsatzplan gespeichert.');refresh()});qsa('[data-plan-delete]').forEach(b=>b.onclick=()=>{write('jma_plans',arr('jma_plans').filter(x=>x.id!==b.dataset.planDelete));refresh()})}

function renderGuides(){const guides=AD().guides?.guides||[],q=read('jma_guides_q',''),cat=read('jma_guides_cat','all'),cats=[...new Set(guides.map(g=>g.category))],rows=guides.filter(g=>(cat==='all'||g.category===cat)&&(!q||`${g.title} ${g.summary} ${g.chapters.map(c=>c.title+' '+c.text).join(' ')}`.toLowerCase().includes(q.toLowerCase())));return `<section class="rf-page guides-page">${hero('WISSEN // SCHRITT FÜR SCHRITT','GUIDES','Onboarding- und Funktionsguides aus dem vorhandenen Projektstand – mit Kapiteln statt reiner Linkliste.',metrics([[guides.length,'Guides'],[guides.reduce((a,g)=>a+g.chapters.length,0),'Kapitel']]))}<div class="rf-guide-toolbar"><input id="guideSearch" value="${esc(q)}" placeholder="Guide oder Kapitel suchen …"><select id="guideCategory"><option value="all">Alle Kategorien</option>${cats.map(c=>`<option ${c===cat?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="rf-guide-grid">${rows.map((g,i)=>`<article><small>${esc(g.category)}</small><h2>${esc(g.title)}</h2><p>${esc(g.summary)}</p><button class="cyan-btn compact" type="button" data-guide-toggle="${i}">KAPITEL ANZEIGEN</button><div class="rf-guide-chapters" data-guide-chapters="${i}" hidden>${g.chapters.map(c=>`<section><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p></section>`).join('')}</div></article>`).join('')||empty('Keine Guides gefunden')}</div></section>`}
function bindGuides(){navBinds();on('#guideSearch','input',e=>inputRefresh('jma_guides_q',e.target.value,'#guideSearch'));on('#guideCategory','change',e=>{write('jma_guides_cat',e.target.value);refresh()});qsa('[data-guide-toggle]').forEach(b=>b.onclick=()=>{const p=qs(`[data-guide-chapters="${b.dataset.guideToggle}"]`);p.hidden=!p.hidden;b.textContent=p.hidden?'KAPITEL ANZEIGEN':'KAPITEL SCHLIESSEN'})}

function renderPatchwatch(){const rows=catalog(),today=new Date('2026-09-28'),stats={};rows.forEach(x=>stats[x.status]=(stats[x.status]||0)+1);const review=rows.map(x=>({...x,age:Math.floor((today-new Date(x.last_checked||'2026-01-01'))/86400000)})).sort((a,b)=>b.age-a.age);return `<section class="rf-page patch-page">${hero('DATENQUALITÄT // MONITOR','PATCH-WÄCHTER','Prüfstatus und Alter der übernommenen Katalogdaten sichtbar machen, ohne ungeprüfte Änderungen als Fakten auszugeben.')}${metrics(Object.entries(stats).map(([k,v])=>[v,k]))}<div class="rf-patch-board"><section class="rf-panel"><div class="rf-panel-head"><b>PRÜFQUEUE</b><small>älteste zuerst</small></div>${review.map(x=>`<article class="rf-patch-row"><div><small>${esc(x.status||'offen')}</small><b>${esc(x.name_de)}</b><span>zuletzt geprüft: ${esc(x.last_checked||'—')}</span></div><em>${x.age} Tage</em><button type="button" data-patch-note="${esc(x.id)}">LOKAL NOTIEREN</button></article>`).join('')}</section><aside class="rf-panel"><div class="rf-panel-head"><b>LOKALE PRÜFNOTIZEN</b><small>${arr('jma_patch_notes').length}</small></div>${arr('jma_patch_notes').map(n=>`<p><b>${esc(n.name)}</b><span>${fmt(n.date)}</span></p>`).join('')||'<p>Noch keine lokalen Notizen.</p>'}</aside></div></section>`}
function bindPatchwatch(){navBinds();qsa('[data-patch-note]').forEach(b=>b.onclick=()=>{const x=catalog().find(v=>v.id===b.dataset.patchNote),rows=arr('jma_patch_notes');rows.unshift({id:b.dataset.patchNote,name:x?.name_de||b.dataset.patchNote,date:new Date().toISOString()});write('jma_patch_notes',rows.slice(0,30));toast('Lokale Prüfnotiz gespeichert.');refresh()})}

function renderSecrets(){const rows=AD().seed?.secrets||[],status=read('jma_secret_status','all'),notes=arr('jma_secret_notes'),filtered=status==='all'?rows:rows.filter(x=>x.status===status),statuses=[...new Set(rows.map(x=>x.status))];return `<section class="rf-page secrets-page">${hero('KANINCHENBAU // ANALYSE','GEHEIMNISSE & UNTERSUCHUNGEN','Methodische Hinweise und Prüfstände aus dem bestehenden Projekt – bestätigt und in Prüfung klar getrennt.')}
 <div class="rf-tabs"><button class="${status==='all'?'active':''}" data-secret-status="all">ALLE</button>${statuses.map(s=>`<button class="${status===s?'active':''}" data-secret-status="${esc(s)}">${esc(s.toUpperCase())}</button>`).join('')}</div><div class="rf-secret-grid">${filtered.map(s=>`<article><div class="rf-secret-risk ${s.risk.toLowerCase()}">${esc(s.risk)}</div><small>${esc(s.category)} · ${esc(s.status)}</small><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p><footer><span>${esc(s.evidence)}</span><button type="button" data-secret-note="${esc(s.id)}">＋ NOTIZ</button></footer></article>`).join('')}</div><section class="rf-panel rf-notebook"><div class="rf-panel-head"><b>MEIN NOTIZBUCH</b><small>${notes.length}</small></div>${notes.map(n=>`<div><b>${esc(n.title)}</b><span>${esc(n.text)}</span><button data-secret-delete="${esc(n.id)}">×</button></div>`).join('')||'<p>Noch keine Untersuchungsnotiz gespeichert.</p>'}</section></section>`}
function bindSecrets(){navBinds();qsa('[data-secret-status]').forEach(b=>b.onclick=()=>{write('jma_secret_status',b.dataset.secretStatus);refresh()});qsa('[data-secret-note]').forEach(b=>b.onclick=()=>{const s=(AD().seed?.secrets||[]).find(x=>x.id===b.dataset.secretNote),text=prompt('Deine lokale Notiz zu diesem Thema:','');if(text===null||!text.trim())return;const rows=arr('jma_secret_notes');rows.unshift({id:uid('secret-note'),source:s?.id,title:s?.title||'Notiz',text:text.trim()});write('jma_secret_notes',rows);refresh()});qsa('[data-secret-delete]').forEach(b=>b.onclick=()=>{write('jma_secret_notes',arr('jma_secret_notes').filter(x=>x.id!==b.dataset.secretDelete));refresh()})}

const buildSlots=()=>AD().r9?.buildPlanner?.slots||[];
function buildOptions(slot){const d=AD(),c=catalog();if(/Primär|Sekundär|Nahkampf/.test(slot))return (d.r12?.weapons||[]).map(x=>x.name);if(['Helm','Maske','Oberteil','Handschuhe','Hose','Schuhe'].includes(slot))return [...new Set([...(d.r9?.armorBlueprints||[]).filter(x=>x.slot===slot).map(x=>x.name),...(d.r9?.mods?.samples||[]).filter(x=>x.slot===slot||x.slot==='Alle Waffen').map(x=>x.name)])];if(slot==='Abweichler')return (d.r9?.deviations||[]).map(x=>x.name);if(slot==='Nahrung')return c.filter(x=>/Fleisch|Food|Nahrung|Verbrauch/i.test(`${x.name_de} ${x.kind}`)).map(x=>x.name_de);if(slot==='Cradle')return [];return c.slice(0,20).map(x=>x.name_de)}
function currentBuild(){return read('jma_build_draft',{id:null,name:'Neuer Build',mode:'Eigener Build',effect:'',notes:'',slots:{},template:null})}
function renderBuilds(){const d=AD(),draft=currentBuild(),saved=arr('jma_saved_builds'),templates=d.seed?.builds||[],slots=buildSlots();const filled=slots.filter(s=>draft.slots?.[s]).length,base=templates.find(x=>x.id===draft.template);return `<section class="rf-page builds-page">${hero('WERKSTATT // LOADOUT','BUILD-PLANER','Waffen, Rüstung, Abweichler, Cradle und Nahrung in einem speicherbaren Loadout zusammenstellen – basierend auf den vorhandenen Planner-Slots.',metrics([[slots.length,'Slots'],[filled,'belegt'],[saved.length,'gespeichert']]))}
 <div class="rf-build-layout"><aside class="rf-panel rf-build-meta"><div class="rf-panel-head"><b>BUILD-PROFIL</b><small>lokaler Entwurf</small></div><label>NAME<input id="buildName" value="${esc(draft.name)}"></label><label>VORLAGE<select id="buildTemplate"><option value="">Eigener Build</option>${templates.map(t=>`<option value="${esc(t.id)}" ${draft.template===t.id?'selected':''}>${esc(t.name)} · ${esc(t.role)}</option>`).join('')}</select></label><label>EFFEKT-FOKUS<select id="buildEffect"><option value="">Kein Fokus</option>${(d.r9?.buildPlanner?.effectFilters||[]).map(x=>`<option ${draft.effect===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>NOTIZ<textarea id="buildNotes">${esc(draft.notes||'')}</textarea></label><div class="rf-action-stack"><button class="cyan-btn compact" id="buildSave" type="button">BUILD SPEICHERN</button><button class="ghost-btn" id="buildClear" type="button">ENTWURF LEEREN</button></div>${base?`<div class="rf-template-stats"><small>VORLAGEN-VERGLEICHSWERTE</small>${Object.entries(base.stats||{}).map(([k,v])=>`<div><span>${esc(k)}</span><i><em style="width:${v}%"></em></i><b>${v}</b></div>`).join('')}<p>${esc(base.notes||'')}</p></div>`:''}</aside>
 <main class="rf-build-slots">${slots.map((s,i)=>`<article><header><span>${String(i+1).padStart(2,'0')}</span><div><small>SLOT</small><b>${esc(s)}</b></div></header><select data-build-slot="${esc(s)}"><option value="">Nicht belegt</option>${buildOptions(s).map(x=>`<option ${draft.slots?.[s]===x?'selected':''}>${esc(x)}</option>`).join('')}</select><p>${draft.slots?.[s]?esc(draft.slots[s]):'Wähle einen bekannten Eintrag aus dem vorhandenen Datenbestand.'}</p></article>`).join('')}</main>
 <aside class="rf-panel rf-build-saved"><div class="rf-panel-head"><b>GESPEICHERT</b><small>${saved.length}</small></div>${saved.map(b=>`<article><div><small>${esc(b.mode||'Build')} · ${fmt(b.updated)}</small><h3>${esc(b.name)}</h3><p>${Object.values(b.slots||{}).filter(Boolean).length}/${slots.length} Slots</p></div><div><button data-build-load="${esc(b.id)}">LADEN</button><button data-build-delete="${esc(b.id)}">×</button></div></article>`).join('')||empty('Noch kein Build gespeichert')}<button class="ghost-btn" id="buildShare" type="button" ${saved.length?'':'disabled'}>AKTUELLEN BUILD ALS JSON KOPIEREN</button></aside></div></section>`}
function bindBuilds(){navBinds();const patch=(k,v)=>{const b=currentBuild();b[k]=v;write('jma_build_draft',b)};on('#buildName','input',e=>patch('name',e.target.value));on('#buildNotes','input',e=>patch('notes',e.target.value));on('#buildEffect','change',e=>patch('effect',e.target.value));on('#buildTemplate','change',e=>{const b=currentBuild(),t=(AD().seed?.builds||[]).find(x=>x.id===e.target.value);b.template=t?.id||null;b.mode=t?`${t.role} · ${t.rating}`:'Eigener Build';if(t){b.name=t.name;b.notes=t.notes||''}write('jma_build_draft',b);refresh()});qsa('[data-build-slot]').forEach(s=>s.onchange=()=>{const b=currentBuild();b.slots={...(b.slots||{}),[s.dataset.buildSlot]:s.value};write('jma_build_draft',b);const p=s.parentElement.querySelector('p');if(p)p.textContent=s.value||'Wähle einen bekannten Eintrag aus dem vorhandenen Datenbestand.'});on('#buildSave','click',()=>{const b=currentBuild(),rows=arr('jma_saved_builds'),id=b.id||uid('build'),obj={...b,id,updated:new Date().toISOString()};const idx=rows.findIndex(x=>x.id===id);idx>=0?rows.splice(idx,1,obj):rows.unshift(obj);write('jma_saved_builds',rows);write('jma_build_draft',obj);toast('Build gespeichert.');refresh()});on('#buildClear','click',()=>{write('jma_build_draft',{id:null,name:'Neuer Build',mode:'Eigener Build',effect:'',notes:'',slots:{},template:null});refresh()});qsa('[data-build-load]').forEach(b=>b.onclick=()=>{const x=arr('jma_saved_builds').find(v=>v.id===b.dataset.buildLoad);if(x){write('jma_build_draft',x);refresh()}});qsa('[data-build-delete]').forEach(b=>b.onclick=()=>{write('jma_saved_builds',arr('jma_saved_builds').filter(x=>x.id!==b.dataset.buildDelete));refresh()});on('#buildShare','click',async()=>{const text=JSON.stringify(currentBuild(),null,2);try{await navigator.clipboard.writeText(text);toast('Build-JSON kopiert.')}catch{prompt('Build-JSON kopieren:',text)}})}

const rooms=[['hilfe','Archiv-Hilfe','Fragen zu Katalog, Karte und Werkzeugen'],['funde','Funde & Korrekturen','Wissen gemeinsam prüfen'],['builds','Build-Labor','Loadouts und Ideen diskutieren']];
function renderCommunity(){const room=read('jma_community_room','hilfe'),posts=arr('jma_community_posts').filter(x=>x.room===room);return `<section class="rf-page community-page">${hero('COMMUNITY // LOKALER PROTOTYP','COMMUNITY','Themenräume und Beiträge sind funktional als lokaler Browserzustand umgesetzt; ein Server-Backend ist im aktuellen Projekt noch nicht angeschlossen.')}
 <div class="rf-community-layout"><aside class="rf-room-list">${rooms.map(r=>`<button class="${room===r[0]?'active':''}" data-room="${r[0]}"><b>${r[1]}</b><span>${r[2]}</span><em>${arr('jma_community_posts').filter(x=>x.room===r[0]).length}</em></button>`).join('')}</aside><main class="rf-community-feed"><div class="rf-panel-head"><b>${esc(rooms.find(r=>r[0]===room)?.[1])}</b><small>lokal gespeichert</small></div>${posts.map(p=>`<article><header><b>${esc(p.author)}</b><small>${fmt(p.created)}</small></header><p>${esc(p.text)}</p><footer><button data-post-like="${esc(p.id)}">♡ ${p.likes||0}</button><button data-post-delete="${esc(p.id)}">LÖSCHEN</button></footer></article>`).join('')||empty('Noch keine Beiträge in diesem Raum')}<form id="communityForm"><textarea name="text" required placeholder="Beitrag schreiben …"></textarea><button class="cyan-btn compact" type="submit">BEITRAG LOKAL SPEICHERN</button></form></main></div></section>`}
function bindCommunity(){navBinds();qsa('[data-room]').forEach(b=>b.onclick=()=>{write('jma_community_room',b.dataset.room);refresh()});on('#communityForm','submit',e=>{e.preventDefault();const text=new FormData(e.currentTarget).get('text').trim();if(!text)return;const rows=arr('jma_community_posts'),a=account();rows.unshift({id:uid('post'),room:read('jma_community_room','hilfe'),author:a?.name||'Lokaler Nutzer',text,created:new Date().toISOString(),likes:0});write('jma_community_posts',rows);refresh()});qsa('[data-post-like]').forEach(b=>b.onclick=()=>{const rows=arr('jma_community_posts'),x=rows.find(p=>p.id===b.dataset.postLike);if(x)x.likes=(x.likes||0)+1;write('jma_community_posts',rows);refresh()});qsa('[data-post-delete]').forEach(b=>b.onclick=()=>{write('jma_community_posts',arr('jma_community_posts').filter(x=>x.id!==b.dataset.postDelete));refresh()})}

function renderSubmissions(){const rows=arr('jma_submissions');return `<section class="rf-page submissions-page">${hero('COMMUNITY // PRÜFQUEUE','EINREICHUNGEN','Funde, Korrekturen und Tech-Formeln strukturiert erfassen. Im aktuellen statischen Projekt werden sie lokal gespeichert und klar nicht als veröffentlicht ausgegeben.')}
 <div class="rf-submit-layout"><form class="rf-panel" id="submissionForm"><div class="rf-panel-head"><b>NEUE EINREICHUNG</b><small>lokaler Entwurf</small></div><label>TYP<select name="type"><option>Fund / Ort</option><option>Katalog-Korrektur</option><option>Tech-Formel</option><option>Guide-Hinweis</option></select></label><label>TITEL<input name="title" required></label><label>BEOBACHTUNG<textarea name="body" required></textarea></label><label>BELEG / QUELLE<textarea name="evidence" placeholder="Eigene Beobachtung, Screenshot-Hinweis oder Quellenvermerk"></textarea></label><button class="cyan-btn compact" type="submit">IN LOKALE PRÜFQUEUE</button></form><section class="rf-panel"><div class="rf-panel-head"><b>MEINE EINREICHUNGEN</b><small>${rows.length}</small></div>${rows.map(x=>`<article class="rf-submission-row"><div><small>${esc(x.type)} · ${fmt(x.created)}</small><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><em>Status: ${esc(x.status)}</em></div><button data-sub-delete="${esc(x.id)}">×</button></article>`).join('')||empty('Noch keine lokalen Einreichungen')}</section></div></section>`}
function bindSubmissions(){navBinds();on('#submissionForm','submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),rows=arr('jma_submissions');rows.unshift({id:uid('submission'),type:fd.get('type'),title:String(fd.get('title')).trim(),body:String(fd.get('body')).trim(),evidence:String(fd.get('evidence')||'').trim(),status:'lokal · nicht veröffentlicht',created:new Date().toISOString()});write('jma_submissions',rows);toast('Einreichung lokal gespeichert.');refresh()});qsa('[data-sub-delete]').forEach(b=>b.onclick=()=>{write('jma_submissions',arr('jma_submissions').filter(x=>x.id!==b.dataset.subDelete));refresh()})}

function renderProfile(){const a=account();const keys=['jma_favorites','jma_hunt','jma_saved_builds','jma_routes','jma_plans','jma_submissions','jma_community_posts'];const counts=keys.map(k=>arr(k).length);return `<section class="rf-page profile-page">${hero('KONTO // LOKAL','PROFIL & DATEN',a?`Lokales Profil für ${a.name||a.email}. Anmeldung und persönliche Werkzeuge verwenden denselben Browserzustand.`:'Noch keine lokale Sitzung aktiv. Nutze die vorhandene Anmeldung oder Registrierung in der Kopfzeile.')}
 <div class="rf-profile-grid"><section class="rf-panel rf-profile-card"><div class="rf-avatar">${esc((a?.name||a?.email||'?')[0].toUpperCase())}</div><small>ANZEIGENAME</small><h2>${esc(a?.name||'Nicht angemeldet')}</h2><p>${esc(a?.email||'—')}</p>${a?`<form id="profileNameForm"><input name="name" value="${esc(a.name||'')}" required minlength="2"><button class="cyan-btn compact">NAME SPEICHERN</button></form>`:'<button class="cyan-btn compact" id="profileLogin" type="button">ANMELDEN</button>'}</section><section class="rf-panel"><div class="rf-panel-head"><b>PERSÖNLICHE DATEN</b><small>lokaler Speicher</small></div>${metrics([[counts[0],'Favoriten'],[counts[1],'Jagdziel(e)'],[counts[2],'Builds'],[counts[3],'Routen']])}<div class="rf-action-stack"><button class="ghost-btn" id="profileExport" type="button">DATEN EXPORTIEREN</button><button class="ghost-btn danger" id="profileClear" type="button">WERKZEUGDATEN LÖSCHEN</button></div><p class="rf-note">Passwort-/Sitzungsdaten werden nicht in den Export aufgenommen.</p></section><section class="rf-panel wide"><div class="rf-panel-head"><b>ARCHIV-VERKNÜPFUNGEN</b><small>direkt weiterarbeiten</small></div><div class="rf-profile-links">${btnLink('collection','★ Sammlung')}${btnLink('hunt','◎ Jagdliste')}${btnLink('builds','⚒ Builds')}${btnLink('planner','◷ Einsätze')}</div></section></div></section>`}
function bindProfile(){navBinds();on('#profileLogin','click',()=>qs('#loginOpen')?.click());on('#profileNameForm','submit',e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name').trim(),sess=read('jma_session',null),acc=read('jma_account',null);if(sess){sess.name=name;write('jma_session',sess)}if(acc){acc.name=name;write('jma_account',acc)}toast('Anzeigename gespeichert.');refresh()});on('#profileExport','click',()=>{const out={exported:new Date().toISOString()};['jma_favorites','jma_hunt','jma_hunt_meta','jma_saved_builds','jma_routes','jma_plans','jma_submissions','jma_community_posts','jma_found','jma_custom_markers'].forEach(k=>{if(localStorage.getItem(k)!==null)out[k]=read(k)});const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='jazzemeow-archiv-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)});on('#profileClear','click',()=>{if(!confirm('Lokale Werkzeugdaten löschen? Konto/Anmeldung bleiben erhalten.'))return;['jma_favorites','jma_hunt','jma_hunt_meta','jma_saved_builds','jma_build_draft','jma_routes','jma_route_draft','jma_plans','jma_submissions','jma_community_posts','jma_found','jma_custom_markers'].forEach(k=>localStorage.removeItem(k));toast('Werkzeugdaten gelöscht.');refresh()})}

function renderCollection(){const fav=set('jma_favorites'),found=set('jma_found'),mode=read('jma_collection_mode','all');let rows=catalog().filter(x=>fav.has(x.id)||found.has(x.id));if(mode==='fav')rows=rows.filter(x=>fav.has(x.id));if(mode==='found')rows=rows.filter(x=>found.has(x.id));return `<section class="rf-page collection-page">${hero('PERSÖNLICH // KATALOG','MEINE SAMMLUNG','Favoriten und als gefunden markierte Katalogeinträge getrennt vom öffentlichen Datenbestand verwalten.',metrics([[fav.size,'Favoriten'],[found.size,'gefunden']]))}<div class="rf-tabs"><button class="${mode==='all'?'active':''}" data-collection-mode="all">ALLE</button><button class="${mode==='fav'?'active':''}" data-collection-mode="fav">FAVORITEN</button><button class="${mode==='found'?'active':''}" data-collection-mode="found">GEFUNDEN</button></div><div class="rf-collection-grid">${rows.map(x=>`<article><small>${esc(x.kind||x.category)}</small><h3>${esc(x.name_de)}</h3><p>${esc(x.description||'')}</p><div class="rf-chips">${fav.has(x.id)?'<span>★ Favorit</span>':''}${found.has(x.id)?'<span>✓ Gefunden</span>':''}</div><div class="actions"><button data-found-toggle="${esc(x.id)}">${found.has(x.id)?'GEFUNDEN AUFHEBEN':'ALS GEFUNDEN'}</button><button data-fav-toggle="${esc(x.id)}">${fav.has(x.id)?'FAVORIT ENTFERNEN':'FAVORIT'}</button></div></article>`).join('')||empty('Sammlung ist leer')}<div class="rf-inline-cta">${btnLink('database','DATENBANK DURCHSUCHEN','cyan-btn compact')}</div></div></section>`}
function bindCollection(){navBinds();qsa('[data-collection-mode]').forEach(b=>b.onclick=()=>{write('jma_collection_mode',b.dataset.collectionMode);refresh()});qsa('[data-found-toggle]').forEach(b=>b.onclick=()=>{const s=set('jma_found'),id=b.dataset.foundToggle;s.has(id)?s.delete(id):s.add(id);putSet('jma_found',s);refresh()});qsa('[data-fav-toggle]').forEach(b=>b.onclick=()=>{const s=set('jma_favorites'),id=b.dataset.favToggle;s.has(id)?s.delete(id):s.add(id);putSet('jma_favorites',s);refresh()})}

function filterSearch(rows,q,fn=x=>JSON.stringify(x)){q=(q||'').trim().toLowerCase();return q?rows.filter(x=>fn(x).toLowerCase().includes(q)):rows}
function renderWeaponBlueprints(){const rows=AD().r9?.weaponBlueprints||[],q=read('jma_wb_q',''),fam=read('jma_wb_family','all'),families=[...new Set(rows.map(x=>x.family))],view=filterSearch(rows.filter(x=>fam==='all'||x.family===fam),q,x=>`${x.name} ${x.family} ${x.rarity}`);return `<section class="rf-page arsenal-page">${hero('DATENBANK // ARSENAL','WAFFEN-BLAUPAUSEN','Blaupausen nach Familie, Seltenheit und offensiven Referenzwerten durchsuchen.',metrics([[rows.length,'Blaupausen'],[families.length,'Familien']]))}<div class="rf-special-toolbar"><input id="wbSearch" value="${esc(q)}" placeholder="Waffe suchen …"><select id="wbFamily"><option value="all">Alle Familien</option>${families.map(x=>`<option ${x===fam?'selected':''}>${esc(x)}</option>`).join('')}</select>${btnLink('compare-weapons','⇄ VERGLEICH ÖFFNEN')}</div><div class="rf-arsenal-grid">${view.map(x=>`<article><div class="rf-weapon-mark">⌁</div><small>${esc(x.rarity)} · ${esc(x.family)}</small><h2>${esc(x.name)}</h2><div class="rf-stat-bars">${[['Krit-Rate',x.critRate],['Krit-Schaden',x.critDmg],['Schwachstelle',x.weakspot]].map(([k,v])=>`<div><span>${k}</span><i><em style="width:${Math.min(100,v)}%"></em></i><b>${v}%</b></div>`).join('')}</div></article>`).join('')}</div></section>`}
function bindWeaponBlueprints(){navBinds();on('#wbSearch','input',e=>inputRefresh('jma_wb_q',e.target.value,'#wbSearch'));on('#wbFamily','change',e=>{write('jma_wb_family',e.target.value);refresh()})}

function renderArmorBlueprints(){const rows=AD().r9?.armorBlueprints||[],slot=read('jma_ab_slot','all'),slots=[...new Set(rows.map(x=>x.slot))],view=rows.filter(x=>slot==='all'||x.slot===slot);return `<section class="rf-page armor-page">${hero('DATENBANK // SCHUTZ','RÜSTUNGS-BLAUPAUSEN','Rüstungsteile nach Slot, Familie, Tier und hinterlegten Basiswerten ansehen.')}
 <div class="rf-tabs"><button class="${slot==='all'?'active':''}" data-armor-slot="all">ALLE</button>${slots.map(s=>`<button class="${slot===s?'active':''}" data-armor-slot="${esc(s)}">${esc(s.toUpperCase())}</button>`).join('')}</div><div class="rf-armor-grid">${view.map(x=>`<article><div class="rf-armor-icon">⬡</div><small>${esc(x.slot)} · ${esc(x.family)} · Tier ${x.tier}</small><h2>${esc(x.name)}</h2><div class="rf-kv"><span><small>LP</small><b>${x.hp}</b></span><span><small>PSI</small><b>${x.psi}</b></span><span><small>VERSCHMUTZUNG</small><b>${x.pollution}</b></span><span><small>HALTBARKEIT</small><b>${x.durability}</b></span></div></article>`).join('')}</div>${btnLink('compare-armors','RÜSTUNG VERGLEICHEN','cyan-btn compact')}</section>`}
function bindArmorBlueprints(){navBinds();qsa('[data-armor-slot]').forEach(b=>b.onclick=()=>{write('jma_ab_slot',b.dataset.armorSlot);refresh()})}

function renderArmorMaterials(){const rows=AD().r9?.armorMaterials?.samples||[],q=read('jma_am_q',''),view=filterSearch(rows,q,x=>`${x.name} ${x.source} ${x.summary}`);return `<section class="rf-page materials-page">${hero('DATENBANK // MATERIALKUNDE','RÜSTUNGSMATERIALIEN',`${AD().r9?.armorMaterials?.count||rows.length} Materialien im Referenzbestand; hier die kuratierte Auswahl mit Herkunft und Kurzfunktion.`)}<div class="rf-special-toolbar"><input id="amSearch" value="${esc(q)}" placeholder="Material, Quelle oder Effekt suchen …"></div><div class="rf-material-list">${view.map(x=>`<article><div><small>QUALITÄT ${x.quality} · ${x.weight} KG · STAPEL ${x.stack}</small><h3>${esc(x.name)}</h3><p>${esc(x.summary)}</p></div><aside><small>QUELLE</small><b>${esc(x.source)}</b></aside></article>`).join('')}</div></section>`}
function bindArmorMaterials(){navBinds();on('#amSearch','input',e=>inputRefresh('jma_am_q',e.target.value,'#amSearch'))}

function renderDeviations(){const rows=AD().r9?.deviations||[],type=read('jma_dev_type','all'),types=[...new Set(rows.map(x=>x.type))],view=rows.filter(x=>type==='all'||x.type===type);return `<section class="rf-page deviation-page">${hero('DATENBANK // ANOMALIE','ABWEICHLER','Abweichler und Varianten nach Typ, Aktion und Zielverhalten sortiert.')}
 <div class="rf-tabs"><button class="${type==='all'?'active':''}" data-dev-type="all">ALLE</button>${types.map(t=>`<button class="${type===t?'active':''}" data-dev-type="${esc(t)}">${esc(t.toUpperCase())}</button>`).join('')}</div><div class="rf-deviation-grid">${view.map(x=>`<article><span class="rf-deviation-orb">Ψ</span><small>${esc(x.type)}</small><h3>${esc(x.name)}</h3><div class="rf-kv"><span><small>AKTION</small><b>${esc(x.action)}</b></span><span><small>ZIEL</small><b>${esc(x.target)}</b></span></div></article>`).join('')}</div></section>`}
function bindDeviations(){navBinds();qsa('[data-dev-type]').forEach(b=>b.onclick=()=>{write('jma_dev_type',b.dataset.devType);refresh()})}

function renderMods(){const d=AD().r9?.mods||{},rows=d.samples||[],slot=read('jma_mod_slot','all'),q=read('jma_mod_q',''),slots=[...new Set(rows.map(x=>x.slot))],view=filterSearch(rows.filter(x=>slot==='all'||x.slot===slot),q,x=>`${x.name} ${x.slot} ${x.tier}`);return `<section class="rf-page mods-page">${hero('DATENBANK // MODIFIKATION','MODS',`${d.countVisibleFilter||rows.length} Einträge im referenzierten Filterstand; die lokale Auswahl zeigt Slot und Tier.`)}<div class="rf-special-toolbar"><input id="modSearch" value="${esc(q)}" placeholder="Mod suchen …"><select id="modSlot"><option value="all">Alle Slots</option>${slots.map(s=>`<option ${s===slot?'selected':''}>${esc(s)}</option>`).join('')}</select></div><div class="rf-mod-matrix">${view.map(x=>`<article><span>⚙</span><div><small>TIER ${esc(x.tier)} · ${esc(x.slot)}</small><h3>${esc(x.name)}</h3></div></article>`).join('')}</div><div class="rf-chips">${(d.families||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div></section>`}
function bindMods(){navBinds();on('#modSearch','input',e=>inputRefresh('jma_mod_q',e.target.value,'#modSearch'));on('#modSlot','change',e=>{write('jma_mod_slot',e.target.value);refresh()})}

const metric=(x,key)=>key==='dps'?((+x.damage||0)*(+x.fireRate||0)/60):(+x[key]||0);
const norm=(rows,key,val)=>{const nums=rows.map(x=>metric(x,key)),min=Math.min(...nums),max=Math.max(...nums);return max===min?100:(metric({[key]:val},key)-min)/(max-min)*100};
const normMetric=(rows,key,item)=>{const nums=rows.map(x=>metric(x,key)),min=Math.min(...nums),max=Math.max(...nums),val=metric(item,key);return max===min?100:(val-min)/(max-min)*100};
function renderCompareWeapons(){const rows=AD().r12?.weapons||[],modes=AD().r12?.weaponCompareModes||{},mode=read('jma_cmp_mode','dps'),ids=read('jma_cmp_ids',rows.slice(0,3).map(x=>x.id)),sel=[0,1,2].map(i=>rows.find(x=>x.id===ids[i])||rows[i%rows.length]);const weights=modes[mode]?.weights||{};const score=w=>Object.entries(weights).reduce((s,[k,wt])=>s+normMetric(rows,k,w)*wt,0);return `<section class="rf-page compare-page">${hero('LABOR // TRANSPARENTER INDEX','WAFFENVERGLEICH','Bis zu drei Waffen nebeneinander mit offen sichtbaren Gewichtungen. Mechanik-/Build-Synergien werden nicht als pauschaler versteckter Bonus behauptet.')}
 <div class="rf-compare-controls"><label>FOKUS<select id="cmpMode">${Object.entries(modes).map(([k,v])=>`<option value="${k}" ${k===mode?'selected':''}>${esc(v.label)}</option>`).join('')}</select></label>${sel.map((w,i)=>`<label>WAFFE ${i+1}<select data-cmp-index="${i}">${rows.map(x=>`<option value="${x.id}" ${x.id===w.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`).join('')}</div>
 <div class="rf-weight-strip">${Object.entries(weights).map(([k,v])=>`<span><b>${esc(k)}</b>${Math.round(v*100)}%</span>`).join('')}</div><div class="rf-compare-grid">${sel.map(w=>`<article><small>${esc(w.family)} · Tier ${w.tier} · ${esc(w.keyword||'')}</small><h2>${esc(w.name)}</h2><div class="rf-score">${score(w).toFixed(1)}</div><span>VERGLEICHSINDEX</span><div class="rf-kv"><span><small>SCHADEN</small><b>${w.damage}</b></span><span><small>FEUERRATE</small><b>${w.fireRate}</b></span><span><small>MAGAZIN</small><b>${w.mag}</b></span><span><small>REICHWEITE</small><b>${w.range}</b></span><span><small>KRIT</small><b>${w.critRate}%</b></span><span><small>SCHWACHSTELLE</small><b>${w.weakspot}%</b></span></div><p>${esc(w.note||'')}</p></article>`).join('')}</div></section>`}
function bindCompareWeapons(){navBinds();on('#cmpMode','change',e=>{write('jma_cmp_mode',e.target.value);refresh()});qsa('[data-cmp-index]').forEach(s=>s.onchange=()=>{const ids=read('jma_cmp_ids',[]);ids[+s.dataset.cmpIndex]=s.value;write('jma_cmp_ids',ids);refresh()})}

function renderCompareArmors(){const rows=AD().r9?.armorCompare||[],ids=read('jma_armor_cmp',[0,1]),a=rows[ids[0]]||rows[0],b=rows[ids[1]]||rows[1]||rows[0],fields=['hp','pollution','psi','capture','durability','movement','glide'];return `<section class="rf-page compare-page armor-compare-page">${hero('LABOR // SCHUTZWERTE','RÜSTUNGSVERGLEICH','Zwei vorhandene Referenzstufen direkt gegenüberstellen; fehlende Werte bleiben sichtbar leer statt erfunden zu werden.')}
 <div class="rf-compare-controls">${[a,b].map((x,i)=>`<label>RÜSTUNG ${i+1}<select data-acmp-index="${i}">${rows.map((r,idx)=>`<option value="${idx}" ${idx===ids[i]?'selected':''}>${esc(r.name)} · Tier ${r.tier}</option>`).join('')}</select></label>`).join('')}</div><div class="rf-armor-compare"><article><small>Tier ${a.tier}</small><h2>${esc(a.name)}</h2></article><article class="rf-delta-table">${fields.map(k=>{const av=a[k],bv=b[k],delta=(typeof av==='number'&&typeof bv==='number')?bv-av:null;return `<div><small>${esc(k.toUpperCase())}</small><b>${av??'—'}</b><em>${delta===null?'—':(delta>0?'+':'')+delta}</em><b>${bv??'—'}</b></div>`}).join('')}</article><article><small>Tier ${b.tier}</small><h2>${esc(b.name)}</h2></article></div></section>`}
function bindCompareArmors(){navBinds();qsa('[data-acmp-index]').forEach(s=>s.onchange=()=>{const ids=read('jma_armor_cmp',[0,1]);ids[+s.dataset.acmpIndex]=+s.value;write('jma_armor_cmp',ids);refresh()})}

function renderMemetics(){const rows=AD().r9?.memetics||[],q=read('jma_mem_q',''),view=filterSearch(rows,q,x=>x);return `<section class="rf-page memetics-page">${hero('DATENBANK // WISSENSKNOTEN','MEMETIK','Referenzliste der vorhandenen Memetik-Namen; Tech-Rework und Werkbank bleiben als eigener Bereich getrennt.')}
 <div class="rf-special-toolbar"><input id="memSearch" value="${esc(q)}" placeholder="Memetik suchen …">${btnLink('tech-workbench','⚙ TECH-WERKBANK')}</div><div class="rf-memetic-list">${view.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><small>MEMETIK</small><h3>${esc(x)}</h3></div><i></i></article>`).join('')}</div></section>`}
function bindMemetics(){navBinds();on('#memSearch','input',e=>inputRefresh('jma_mem_q',e.target.value,'#memSearch'))}

function renderVehicles(){const rows=AD().r9?.vehicles||[],q=read('jma_veh_q',''),view=filterSearch(rows,q,x=>x.name);return `<section class="rf-page vehicles-page">${hero('DATENBANK // MOBILITÄT','FAHRZEUGE','Fahrzeugtypen aus dem Referenzstand inklusive hinterlegter Skin-Zähler.')}
 <div class="rf-special-toolbar"><input id="vehSearch" value="${esc(q)}" placeholder="Fahrzeug suchen …"></div><div class="rf-garage">${view.map(x=>`<article><div class="rf-vehicle-silhouette">▱<i></i></div><small>FAHRZEUGTYP</small><h2>${esc(x.name)}</h2><span>${x.skins} Skin${x.skins===1?'':'s'} im Referenzstand</span></article>`).join('')}</div></section>`}
function bindVehicles(){navBinds();on('#vehSearch','input',e=>inputRefresh('jma_veh_q',e.target.value,'#vehSearch'))}

function renderCreatures(){const d=AD().r9?.creatures||{},q=read('jma_cr_q',''),live=filterSearch(d.livestock||[],q,x=>x),other=filterSearch(d.unconfirmed||[],q,x=>x);return `<section class="rf-page creatures-page">${hero('DATENBANK // FAUNA','KREATUREN','Nutztiere und weitere beobachtete Wildtiere bewusst getrennt; unbestätigte Verfügbarkeit bleibt als solche markiert.')}
 <div class="rf-special-toolbar"><input id="creatureSearch" value="${esc(q)}" placeholder="Kreatur suchen …"></div><div class="rf-creature-cols"><section><div class="rf-panel-head"><b>NUTZTIERE / BESTAND</b><small>${live.length}</small></div><div class="rf-creature-grid">${live.map(x=>`<article><span>◌</span><b>${esc(x)}</b></article>`).join('')}</div></section><section><div class="rf-panel-head"><b>WEITERE WILDTIERE</b><small>Verfügbarkeit unbestätigt · ${other.length}</small></div><div class="rf-creature-grid unconfirmed">${other.map(x=>`<article><span>?</span><b>${esc(x)}</b></article>`).join('')}</div></section></div></section>`}
function bindCreatures(){navBinds();on('#creatureSearch','input',e=>inputRefresh('jma_cr_q',e.target.value,'#creatureSearch'))}

const invMaterials=['Metallschrott','Rostige Teile','Teile','Veredelte Teile','Spezialteil','Plastikabfall','Plastik','Feuerfestes Plastik','Technikplastik','Elektronikteile','Kupferbarren','Stahlbarren','Aluminiumbarren','Wolframbarren'];
function renderTechWorkbench(){const d=AD().r12?.techWorkbench||{},tab=read('jma_tech_tab','reverse'),q=read('jma_tech_q',''),reverse=filterSearch(d.reverseSamples||[],q,x=>`${x.name} ${x.group} ${x.unlock}`),recipeId=read('jma_recipe_id',d.recipes?.[0]?.id),recipe=(d.recipes||[]).find(x=>x.id===recipeId)||d.recipes?.[0],qty=read('jma_recipe_qty',1),inv=read('jma_invention_slots',Array(9).fill(''));return `<section class="rf-page tech-page">${hero('WERKZEUGE // TECH','TECH-WERKBANK','Reverse Engineering, Erfindung und feste Fertigungsformeln bewusst getrennt – mit den vorhandenen R12-Daten statt erfundener Mischlogik.',metrics([[d.reverseCounts?.Alle||0,'Reverse-Einträge'],[d.inventionCounts?.Alle||0,'Erfindungs-Pool'],[(d.recipes||[]).length,'geprüfte Formeln']]))}
 <div class="rf-tabs rf-tech-tabs"><button class="${tab==='reverse'?'active':''}" data-tech-tab="reverse">REVERSE ENGINEERING</button><button class="${tab==='invention'?'active':''}" data-tech-tab="invention">ERFINDUNG</button><button class="${tab==='recipes'?'active':''}" data-tech-tab="recipes">FERTIGUNGSRECHNER</button></div>
 ${tab==='reverse'?`<div class="rf-tech-reverse"><div class="rf-special-toolbar"><input id="techSearch" value="${esc(q)}" placeholder="Werkzeug, Gruppe oder Freischaltung suchen …"></div><div class="rf-tech-counts">${Object.entries(d.reverseCounts||{}).map(([k,v])=>`<span><small>${esc(k)}</small><b>${v}</b></span>`).join('')}</div><div class="rf-tech-table">${reverse.map(x=>`<article><div><small>${esc(x.group)}</small><h3>${esc(x.name)}</h3><p>${esc(x.unlock)}</p></div><span><small>TP / ZYKLUS</small><b>${esc(x.tp)}</b></span><span><small>ZEIT</small><b>${esc(x.time)} s</b></span></article>`).join('')}</div></div>`:''}
 ${tab==='invention'?`<div class="rf-tech-invention"><article class="rf-panel"><div class="rf-panel-head"><b>MATERIAL-MIX PLANEN</b><small>2–9 Materialien</small></div><p>Die vorhandene R12-Logik trennt Erfindung ausdrücklich von festen Rezepten: der Materialmix bestimmt keinen garantiert festen Output.</p><div class="rf-invention-slots">${Array.from({length:9},(_,i)=>`<label>SLOT ${i+1}<select data-inv-slot="${i}"><option value="">leer</option>${invMaterials.map(x=>`<option ${inv[i]===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`).join('')}</div><button class="ghost-btn" id="invClear" type="button">AUSWAHL LEEREN</button></article><aside class="rf-panel"><div class="rf-panel-head"><b>POOL-UMFANG</b><small>Referenzdaten</small></div>${Object.entries(d.inventionCounts||{}).map(([k,v])=>`<div class="rf-count-row"><span>${esc(k)}</span><b>${v}</b></div>`).join('')}</aside></div>`:''}
 ${tab==='recipes'&&recipe?`<div class="rf-recipe-layout"><aside class="rf-panel"><div class="rf-panel-head"><b>FORMEL WÄHLEN</b><small>${d.recipes.length}</small></div><select id="recipeSelect">${d.recipes.map(r=>`<option value="${esc(r.id)}" ${r.id===recipe.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select><label>MENGE<input id="recipeQty" type="number" min="1" max="99" value="${qty}"></label><p><b>${esc(recipe.output)}</b><br>${esc(recipe.unlock)}</p><small>${esc(recipe.verified)} · ${esc(recipe.lastChecked)}</small></aside><main class="rf-panel"><div class="rf-panel-head"><b>MATERIALBEDARF</b><small>${qty}×</small></div><div class="rf-recipe-materials">${recipe.materials.map(m=>`<article><span>${esc(m.name)}</span><b>${m.qty*qty}</b><small>${m.qty} × ${qty}</small></article>`).join('')}</div>${btnLink('submissions','FORMEL / KORREKTUR EINREICHEN')}</main></div>`:''}</section>`}
function bindTechWorkbench(){navBinds();qsa('[data-tech-tab]').forEach(b=>b.onclick=()=>{write('jma_tech_tab',b.dataset.techTab);refresh()});on('#techSearch','input',e=>inputRefresh('jma_tech_q',e.target.value,'#techSearch'));qsa('[data-inv-slot]').forEach(s=>s.onchange=()=>{const a=read('jma_invention_slots',Array(9).fill(''));a[+s.dataset.invSlot]=s.value;write('jma_invention_slots',a)});on('#invClear','click',()=>{write('jma_invention_slots',Array(9).fill(''));refresh()});on('#recipeSelect','change',e=>{write('jma_recipe_id',e.target.value);refresh()});on('#recipeQty','input',e=>inputRefresh('jma_recipe_qty',Math.max(1,+e.target.value||1),'#recipeQty',320))}

function renderExchange(){const posts=arr('jma_exchange_posts'),builds=arr('jma_saved_builds');return `<section class="rf-page exchange-page">${hero('COMMUNITY // WERKSTATT','COMMUNITY-WERKSTATT','Lokales Teilen gespeicherter Builds sowie Suche/Biete-Posts. Echtgeld-Handel ist gemäß vorhandener Projektregel nicht vorgesehen.')}
 <div class="rf-exchange-layout"><form class="rf-panel" id="exchangeForm"><div class="rf-panel-head"><b>BEITRAG ERSTELLEN</b><small>lokal</small></div><label>TYP<select name="type"><option>Build teilen</option><option>Suche</option><option>Biete</option></select></label><label>BUILD<select name="build"><option value="">Kein Build</option>${builds.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label><label>TITEL<input name="title" required></label><label>TEXT<textarea name="text" required></textarea></label><button class="cyan-btn compact">VERÖFFENTLICHUNG LOKAL SIMULIEREN</button><p class="rf-note">Kein Server-Backend: Beitrag bleibt in diesem Browser.</p></form><main class="rf-exchange-feed">${posts.map(p=>{const b=builds.find(x=>x.id===p.build);return `<article><header><small>${esc(p.type)} · ${fmt(p.created)}</small><h2>${esc(p.title)}</h2></header><p>${esc(p.text)}</p>${b?`<div class="rf-shared-build"><b>⚒ ${esc(b.name)}</b><span>${Object.values(b.slots||{}).filter(Boolean).length} belegte Slots</span><button data-exchange-copy="${esc(b.id)}">BUILD KOPIEREN</button></div>`:''}<button data-exchange-delete="${esc(p.id)}">BEITRAG LÖSCHEN</button></article>`}).join('')||empty('Noch keine Werkstatt-Beiträge')}</main></div></section>`}
function bindExchange(){navBinds();on('#exchangeForm','submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),rows=arr('jma_exchange_posts');rows.unshift({id:uid('exchange'),type:fd.get('type'),build:fd.get('build'),title:String(fd.get('title')).trim(),text:String(fd.get('text')).trim(),created:new Date().toISOString()});write('jma_exchange_posts',rows);refresh()});qsa('[data-exchange-delete]').forEach(b=>b.onclick=()=>{write('jma_exchange_posts',arr('jma_exchange_posts').filter(x=>x.id!==b.dataset.exchangeDelete));refresh()});qsa('[data-exchange-copy]').forEach(b=>b.onclick=()=>{const x=arr('jma_saved_builds').find(v=>v.id===b.dataset.exchangeCopy);if(!x)return;const copy={...x,id:uid('build'),name:`${x.name} · Kopie`,updated:new Date().toISOString()};const rows=arr('jma_saved_builds');rows.unshift(copy);write('jma_saved_builds',rows);toast('Build als lokale Kopie gespeichert.')})}

const R={dashboard:renderDashboard,news:renderNews,map:renderMap,hunt:renderHunt,routes:renderRoutes,planner:renderPlanner,guides:renderGuides,patchwatch:renderPatchwatch,secrets:renderSecrets,builds:renderBuilds,community:renderCommunity,submissions:renderSubmissions,profile:renderProfile,collection:renderCollection,'weapon-blueprints':renderWeaponBlueprints,'armor-blueprints':renderArmorBlueprints,'armor-materials':renderArmorMaterials,deviations:renderDeviations,mods:renderMods,'compare-weapons':renderCompareWeapons,'compare-armors':renderCompareArmors,memetics:renderMemetics,vehicles:renderVehicles,creatures:renderCreatures,'tech-workbench':renderTechWorkbench,exchange:renderExchange};
const B={dashboard:navBinds,news:bindNews,map:bindMap,hunt:bindHunt,routes:bindRoutes,planner:bindPlanner,guides:bindGuides,patchwatch:bindPatchwatch,secrets:bindSecrets,builds:bindBuilds,community:bindCommunity,submissions:bindSubmissions,profile:bindProfile,collection:bindCollection,'weapon-blueprints':bindWeaponBlueprints,'armor-blueprints':bindArmorBlueprints,'armor-materials':bindArmorMaterials,deviations:bindDeviations,mods:bindMods,'compare-weapons':bindCompareWeapons,'compare-armors':bindCompareArmors,memetics:bindMemetics,vehicles:bindVehicles,creatures:bindCreatures,'tech-workbench':bindTechWorkbench,exchange:bindExchange};
globalThis.FULL_ROUTE_RENDERERS=R;globalThis.FULL_ROUTE_BINDERS=B;
})();
