const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results/b07-profile'),base='9b21c0c62ec81e600d751525b737721f29cf789a';
fs.mkdirSync(out,{recursive:true});let checks=0;const results=[],errors=[],network=[];
const ok=(condition,label)=>{assert.ok(condition,label);checks++;results.push(label);console.log('PASS',checks,label)};
const originalJs=cp.execFileSync('git',['show',base+':routes-full.js'],{cwd:root,encoding:'utf8'});
const fixture=fs.readFileSync(path.join(__dirname,'auth-fixture.js'),'utf8')+`\n(()=>{const f=supabase.createClient;globalThis.__catalogWrites=0;supabase.createClient=(...a)=>{const c=f(...a),from=c.from.bind(c);c.from=t=>t!=='catalog_entries'?from(t):{select(){return this},order(){return this},range:async(a,b)=>({data:CATALOG_DATA.entries.slice(a,b+1).map(entry=>({id:entry.id,entry,revision:1})),error:null}),insert(){__catalogWrites++;throw Error('Unexpected catalog write')},update(){__catalogWrites++;throw Error('Unexpected catalog write')},delete(){__catalogWrites++;throw Error('Unexpected catalog delete')}};return c}})();`;
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\/$/,'/index.html'));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(b)})});
const tabs=['general','avatar','banner','colors','about','highlights','widgets','frames','decorations','trophies'];
const go=async(page,route,selector)=>{await page.evaluate(route=>location.hash='#/'+route,route);await page.waitForSelector(selector);await page.evaluate(()=>document.fonts.ready)};
const settle=page=>page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('#app img[src]')].map(img=>img.complete?Promise.resolve():new Promise(r=>{img.addEventListener('load',r,{once:true});img.addEventListener('error',r,{once:true})})));document.getAnimations().forEach(a=>{if(a.effect.getComputedTiming().endTime!==Infinity){a.finish()}else{a.pause();a.currentTime=0}});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));document.getAnimations().filter(a=>a instanceof CSSTransition).forEach(a=>a.finish())});
const snapshot=async page=>{await page.mouse.move(0,0);await settle(page);return page.evaluate(()=>[...document.querySelectorAll('#app,#app *')].filter(el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden').map(el=>{const css=getComputedStyle(el),r=el.getBoundingClientRect();return {tag:el.tagName,id:el.id,class:typeof el.className==='string'?el.className:el.className.baseVal,text:[...el.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent.trim()).filter(Boolean).join(' '),rect:[r.x,r.y,r.width,r.height].map(x=>Math.round(x*100)/100),style:Object.fromEntries([...css].map(k=>[k,css.getPropertyValue(k)]))}}))};
const geometry=page=>page.evaluate(()=>{const live=document.querySelector('[data-profile-live]'),stage=document.querySelector('.settings-profile-panel-stage'),work=document.querySelector('.settings-profile-work'),r=live.getBoundingClientRect(),s=stage.getBoundingClientRect();return {height:r.height,width:r.width,y:r.y,stageY:s.y+work.scrollTop+scrollY,workScroll:work.scrollTop,sidebarHeight:document.querySelector('.settings-sidebar').getBoundingClientRect().height}});
(async()=>{await new Promise(r=>server.listen(4186,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/tmp/once-human-chrome/opt/google/chrome/chrome',headless:true,args:['--no-sandbox']});
try{
 const make=async original=>{const ctx=await browser.newContext({viewport:{width:1920,height:1080}});await ctx.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/javascript',body:fixture}));await ctx.route('https://*.supabase.co/**',r=>{network.push(r.request().url());return r.abort()});if(original)await ctx.route('**/routes-full.js*',r=>r.fulfill({contentType:'text/javascript',body:originalJs}));const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4186/#/home');await page.waitForFunction(()=>JMA_AUTH.getState().ready);await page.evaluate(async()=>{await JMA_AUTH.signInWithPassword('preview@example.invalid','test-password');const id=CATALOG_DATA.entries[0].id;JMA_STORE.write('jma_favorites',[id]);JMA_STORE.write('jma_found',[id]);JMA_STORE.write('jma_saved_builds',[{id:'profile-build',name:'Profil-Testbuild',updated:'2026-09-01T00:00:00Z',slots:{}}]);JMA_STORE.write('jma_routes',[{id:'profile-route',name:'Profil-Testroute',markers:[],created:'2026-09-01T00:00:00Z'}]);JMA_STORE.write('jma_achievements',{'first-build':'2026-09-01T00:00:00Z','first-find':'2026-09-01T00:00:00Z','first-route':'2026-09-01T00:00:00Z'});JMA_STORE.write('jma_profile_appearance',{avatar:'critical-pulse',frame:'manibus',banner:'eisfront',color:'gold',ring:'gold',wreath:'laurel',bio:'Profilvorschau',trophy:'first-build'});});return {ctx,page}};
 const {ctx:oldContext,page:oldPage}=await make(true),{ctx,page}=await make(false);
 for(const width of [1920,390]){
  for(const p of [oldPage,page]){await p.setViewportSize({width,height:width===1920?1080:844});await go(p,'profile','.profile-ref-page')}
  for(const view of ['overview','collection']){for(const p of [oldPage,page])await p.locator('[data-profile-view="'+view+'"]').click();const actual=await snapshot(page),expected=await snapshot(oldPage);assert.deepEqual(actual,expected,'Main profile visual parity: '+width+' '+view);ok(true,'Visible profile geometry, text and computed styles preserved: '+width+' / '+view)}
 }
 await oldContext.close();
 await go(page,'profile','.profile-ref-page');await page.locator('[data-profile-view="overview"]').click();
 ok(await page.locator('.profile-ref-drawer,#profileEditBackdrop,[data-profile-choice]').count()===0,'Main profile no longer builds the unreachable hidden drawer and its 95 choices');
 ok(await page.locator('[data-profile-edit-open]').count()===2,'Both existing edit entry points retained');
 ok((await page.locator('.profile-ref-identity').innerText()).includes('Erster Build')&&(await page.locator('.profile-ref-slot-row').innerText()).includes('★'),'Earned trophy badge and favorites showcase preserved');
 for(let i=0;i<2;i++){await go(page,'profile','.profile-ref-page');await page.locator('[data-profile-view="overview"]').click();await page.locator('[data-profile-edit-open]').nth(i).click();await page.waitForSelector('.settings-profile-editor');ok(await page.evaluate(()=>location.hash==='#/settings/profile'),'Edit entry '+(i+1)+' opens the existing settings editor')}
 const measurements=[];
 for(const width of [1920,1280,768,390,360]){
  await page.setViewportSize({width,height:width>=768?1080:844});await page.reload();await page.waitForSelector('[data-profile-live]');await settle(page);
  assert.deepEqual(await page.locator('[data-profile-edit-tab]').evaluateAll(els=>els.map(el=>el.dataset.profileEditTab)),tabs);ok(true,'All ten original categories retained at '+width);
  ok(await page.locator('[data-profile-choice]').count()===95,'All 95 original editor choices retained at '+width);
  const first=await geometry(page);const rows=[];
  for(const tab of tabs){await page.locator('[data-profile-edit-tab="'+tab+'"]').click();const next=await geometry(page);assert.equal(next.height,first.height,'Preview height: '+width+' '+tab);assert.equal(next.stageY,first.stageY,'Content origin: '+width+' '+tab);assert.equal(next.y,first.y,'Preview origin: '+width+' '+tab);assert.equal(next.sidebarHeight,first.sidebarHeight,'Sidebar: '+width+' '+tab);assert.equal(next.workScroll,0);assert.equal(await page.locator('.settings-profile-panel-stage>[data-profile-edit-panel].active').getAttribute('data-profile-edit-panel'),tab);rows.push({tab,...next})}
  measurements.push({width,rows});ok(true,'Preview height, content origin and sidebar stable across all ten categories at '+width);
  await page.locator('[data-profile-edit-tab="banner"]').click();const before=await geometry(page);
  for(const choice of await page.locator('[data-profile-choice="banner"]').all()){await choice.click();assert.equal((await geometry(page)).height,before.height);assert.equal((await geometry(page)).stageY,before.stageY)}
  ok(true,'Every existing banner updates without moving the following content at '+width);
  for(const tab of ['general','banner']){await page.locator('[data-profile-edit-tab="'+tab+'"]').click();await settle(page);await page.screenshot({path:path.join(out,tab+'-'+width+'.png'),fullPage:true})}
 }
 await page.setViewportSize({width:1920,height:1080});await page.reload();await page.waitForSelector('[data-profile-live]');
 await page.fill('#profileNameForm input[name="name"]','B07 Profilprüfung');ok(await page.locator('[data-profile-live-name]').innerText()==='B07 Profilprüfung','Unsaved name updates live preview');
 for(const [tab,field,value] of [['avatar','avatar','critical-pulse'],['frames','frame','manibus'],['banner','banner','eisfront'],['colors','color','violet'],['decorations','ring','gold'],['decorations','wreath','laurel'],['trophies','trophy','first-build']]){await page.locator('[data-profile-edit-tab="'+tab+'"]').click();await page.locator('[data-profile-choice="'+field+'"][data-value="'+value+'"]').click()}
 await page.locator('[data-profile-edit-tab="about"]').click();await page.fill('#profileBio','B07 Vorschau und gespeicherte Profilgestaltung.');
 await page.locator('[data-profile-edit-tab="highlights"]').click();await page.selectOption('#profileHighlight','profile-build');
 await page.locator('[data-profile-edit-tab="widgets"]').click();await page.uncheck('[data-profile-widget="showcase"]');
 ok(await page.locator('[data-profile-live-avatar] .avatar-image').getAttribute('src')==='./assets/profile/avatar-critical-pulse.png'&&await page.locator('[data-profile-live-avatar] .avatar-frame').getAttribute('src')==='./assets/profile/frame-manibus.png','Combined avatar and frame stay present across category switches');
 await page.locator('[data-profile-edit-tab="general"]').click();await page.locator('#profileNameForm button').click();await page.waitForFunction(()=>JMA_AUTH.getAccount().name==='B07 Profilprüfung');await page.reload();await page.waitForSelector('[data-profile-live]');
 const saved=await page.evaluate(()=>JMA_PROFILE.appearance());
 ok(saved.avatar==='critical-pulse'&&saved.frame==='manibus'&&saved.banner==='eisfront'&&saved.color==='violet'&&saved.ring==='gold'&&saved.wreath==='laurel'&&saved.trophy==='first-build'&&saved.highlight==='profile-build'&&saved.bio==='B07 Vorschau und gespeicherte Profilgestaltung.'&&!saved.widgets.includes('showcase'),'General Save and reload preserve all ten categories, name and widget choice');
 await go(page,'profile','.profile-ref-page');await page.locator('[data-profile-view="overview"]').click();ok(await page.locator('.profile-ref-identity h1').innerText()==='B07 Profilprüfung'&&(await page.locator('.profile-ref-identity').innerText()).includes('Erster Build'),'Saved name and earned trophy display on main profile without the drawer');
 ok(await page.locator('.profile-ref-slot-row').evaluate(el=>el.closest('section').hidden),'Showcase widget visibility remains effective');
 await page.setInputFiles('#galleryUpload',path.join(root,'assets/profile/avatar-critical-pulse.png'));await page.waitForFunction(()=>JMA_STORE.read('jma_gallery',[]).length===1);await page.reload();await page.waitForFunction(()=>document.querySelector('#profileGallerySection img')?.naturalWidth>0);ok(true,'Gallery upload and IndexedDB image survive reload');
 await page.locator('[data-profile-view="collection"]').click();ok(await page.locator('[data-profile-view-panel="collection"]').isVisible(),'Integrated collection remains available');await go(page,'collection','[data-profile-view-panel="collection"]');ok(await page.locator('[data-profile-view="collection"]').getAttribute('aria-current')==='page','Existing collection alias still selects collection');
 await go(page,'settings/profile','[data-profile-live]');await page.locator('[data-profile-edit-tab="avatar"]').click();await page.setInputFiles('#avatarUpload',path.join(root,'assets/profile/avatar-critical-pulse.png'));await page.waitForFunction(()=>document.querySelector('[data-profile-live-avatar] img[data-media-id]')?.naturalWidth>0);await page.locator('[data-profile-edit-panel="avatar"] [data-profile-save]').click();await page.waitForFunction(()=>JMA_PROFILE.appearance().avatar.startsWith('upload-'));await page.reload();await page.waitForFunction(()=>document.querySelector('[data-profile-live-avatar] img[data-media-id]')?.naturalWidth>0);ok(true,'Custom avatar upload/save/reload keeps the composed preview');
 await page.click('#profileEditClose');await page.waitForSelector('.settings-controls');ok(await page.evaluate(()=>location.hash==='#/settings'),'Existing back-to-Appearance action preserved');
 ok(await page.evaluate(()=>__catalogWrites===0&&CATALOG_DATA.entries.length===21&&CATALOG_DATA.categories.length===14),'No catalog writes; all entries and categories unchanged');
 ok(network.length===0,'No real Supabase requests or writes during isolated checks');ok(errors.length===0,'No browser JavaScript exceptions');
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({base,checks,results,measurements,errors,network},null,2));await ctx.close();console.log('PASS B07 profile checks:',checks);
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
