const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'), base=JSON.parse(fs.readFileSync(path.join(root,'data-catalog.json'),'utf8'));
const out=path.join(root,'test-results/catalog-storage');fs.mkdirSync(out,{recursive:true});
let checks=0;const ok=(condition,message)=>{assert.ok(condition,message);console.log('PASS',++checks,message)};
const server=http.createServer((req,res)=>{const rel=decodeURIComponent(req.url.split('?')[0]),file=path.join(root,rel==='/'?'index.html':rel);if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(error,bytes)=>{if(error)return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(bytes)})});
const mock=`(()=>{
const initial=${JSON.stringify(base.entries)},read=(k,f)=>JSON.parse(localStorage.getItem('test:'+k)||JSON.stringify(f)),write=(k,v)=>localStorage.setItem('test:'+k,JSON.stringify(v));
const user=read('user',{id:'test-owner',email:'owner@example.invalid',created_at:'2026-09-01T00:00:00Z',user_metadata:{}});let session=read('session',{user}),profile=read('profile',{id:user.id,display_name:'Editor-Test',avatar_url:null});
const db=()=>read('catalog',initial.map(entry=>({id:entry.id,entry,revision:1,updated_at:'2026-10-01T00:00:00Z'})));
const userRole=()=>read('role','owner');
const client={auth:{onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),getSession:async()=>({data:{session}}),signInWithPassword:async()=>({data:{session,user}}),signUp:async()=>({data:{user,session:null}}),signOut:async()=>({error:null}),updateUser:async()=>({data:{user}}),resetPasswordForEmail:async()=>({data:{}})},from(table){let action='select',payload,filters=[];const q={select(){return this},order(){return this},range(start,end){if(table!=='catalog_entries')return Promise.resolve({data:[],error:null});return Promise.resolve({data:db().slice(start,end+1),error:null})},eq(key,value){filters.push([key,value]);return this},update(value){action='update';payload=value;return this},insert(value){action='insert';payload=value;return this},async maybeSingle(){if(table==='profiles')return {data:profile,error:null};if(table==='user_roles')return {data:{user_id:user.id,role:userRole()},error:null};if(table==='catalog_entries'){let rows=db(),row=rows.find(r=>filters.every(([k,v])=>k==='id'?r.id===v:r[k]===v));if(action==='update'){if(!row)return {data:null,error:null};row={...row,...payload};rows=rows.map(r=>r.id===row.id?row:r);write('catalog',rows);return {data:row,error:null}}return {data:row||null,error:null}}return {data:null,error:null}},async single(){if(table==='catalog_entries'&&action==='insert'){const rows=db();if(rows.some(r=>r.id===payload.id))return {data:null,error:{code:'23505',message:'duplicate'}};const row={...payload,revision:1,updated_at:'2026-10-01T00:00:00Z'};rows.push(row);write('catalog',rows);return {data:row,error:null}}return {data:profile,error:null}}};return q}};
globalThis.supabase={createClient:()=>client};})();`;
(async()=>{
 await new Promise(resolve=>server.listen(4181,'127.0.0.1',resolve));
 const browser=await chromium.launch({executablePath:'/tmp/once-human-chrome/opt/google/chrome/chrome',headless:true,args:['--no-sandbox']});
 try{
  const context=await browser.newContext({viewport:{width:1920,height:1080}});
  await context.route('https://cdn.jsdelivr.net/**',route=>route.fulfill({contentType:'text/javascript',body:mock}));
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept());
  await page.addInitScript(()=>{const user={id:'test-owner',email:'owner@example.invalid',created_at:'2026-09-01T00:00:00Z',user_metadata:{}};localStorage.setItem('test:role',JSON.stringify('owner'));localStorage.setItem('test:session',JSON.stringify({user}));sessionStorage.setItem('oha:admin-preview:view','editor')});
  await page.goto('http://127.0.0.1:4181/#/admin');
  await page.waitForFunction(()=>globalThis.JMA_AUTH?.getState().ready&&globalThis.CATALOG_DATA?.entries.length===21);
  await page.waitForSelector('[data-editor-save]');
  ok(await page.locator('[data-editor-card]').count()===21,'Loads the 21 seeded database entries into editor');
  ok(await page.locator('[data-editor-filter]').count()===15,'Existing category filters include all 14 categories');
  ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Editor has no horizontal overflow at desktop');
  await page.screenshot({path:path.join(out,'editor-1920.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Editor has no horizontal overflow at 390px');
  await page.screenshot({path:path.join(out,'editor-390.png'),fullPage:true});
  await page.setViewportSize({width:1920,height:1080});
  const original=base.entries[0];await page.locator('[data-admin-edit-item="'+original.id+'"]').click();
  await page.locator('[data-editor-input="description"]').fill('Persisted editor test update');
  await page.locator('[data-editor-save]').click();
  await page.waitForFunction(()=>{const status=document.querySelector('[data-editor-status]');return status?.querySelector('b')?.textContent==='NICHT GESPEICHERT'||status?.querySelector('p')?.textContent.includes('wurde in Supabase gespeichert')});
  const saveStatus=await page.locator('[data-editor-status]').innerText();if(saveStatus.includes('NICHT GESPEICHERT'))throw new Error('save failed: '+saveStatus);
  ok(await page.evaluate(id=>JMA_CATALOG.revision(id),original.id)===2,'Existing entry saved with a new revision');
  await page.reload();
  await page.waitForFunction(id=>JMA_AUTH?.getState().ready&&CATALOG_DATA.entries.find(e=>e.id===id)?.description==='Persisted editor test update',original.id);
  ok(await page.locator('[data-editor-input="description"]').inputValue()==='Persisted editor test update','Updated record remains after reload');
  await page.locator('[data-editor-add]').click();await page.locator('[data-editor-input="name"]').fill('Editor Test Item');
  await page.locator('[data-editor-category]').selectOption('items');
  await page.locator('[data-editor-save]').click();
  await page.waitForFunction(()=>CATALOG_DATA.entries.some(e=>e.name_de==='Editor Test Item'));
  const newId=await page.evaluate(()=>CATALOG_DATA.entries.find(e=>e.name_de==='Editor Test Item').id);
  ok(await page.evaluate(id=>JMA_CATALOG.revision(id),newId)===1,'New entry receives a stable unique ID and is saved once');
  await page.reload();await page.waitForFunction(id=>JMA_AUTH?.getState().ready&&CATALOG_DATA.entries.some(e=>e.id===id),newId);
  ok(await page.locator('[data-admin-edit-item="'+newId+'"]').count()===1,'New entry remains after reload without duplicate cards');
  await page.locator('[data-editor-add]').click();await page.locator('[data-editor-input="name"]').fill('Editor Test Item');await page.locator('[data-editor-category]').selectOption('items');await page.locator('[data-editor-save]').click();
  ok((await page.locator('[data-editor-status] p').innerText()).includes('gleichnamiger Eintrag'),'Duplicate name/category is rejected');
  await page.locator('[data-editor-add]').click();await page.locator('[data-editor-save]').click();
  ok(await page.locator('[data-editor-input="name"]').evaluate(el=>el.validity.valueMissing),'Required name is blocked by native form validation');
  await page.evaluate(id=>{const rows=JSON.parse(localStorage.getItem('test:catalog'));rows.find(e=>e.id===id).revision+=1;localStorage.setItem('test:catalog',JSON.stringify(rows))},original.id);
  await page.locator('[data-admin-edit-item="'+original.id+'"]').click();await page.locator('[data-editor-input="status"]').fill('stale-write-test');await page.locator('[data-editor-save]').click();
  await page.waitForFunction(()=>document.querySelector('[data-editor-status] p')?.textContent.includes('geändert'));
  ok(await page.evaluate(id=>CATALOG_DATA.entries.find(e=>e.id===id).status,original.id)!=='stale-write-test','Concurrent edit is rejected without overwriting the stored row');
  ok(errors.length===0,'No browser exceptions: '+errors.join('; '));
  const userContext=await browser.newContext({viewport:{width:1280,height:900}});await userContext.route('https://cdn.jsdelivr.net/**',route=>route.fulfill({contentType:'text/javascript',body:mock}));
  const userPage=await userContext.newPage();await userPage.addInitScript(()=>{const user={id:'test-user',email:'user@example.invalid',user_metadata:{}};localStorage.setItem('test:role',JSON.stringify('user'));localStorage.setItem('test:session',JSON.stringify({user}))});
  await userPage.goto('http://127.0.0.1:4181/#/home');await userPage.waitForFunction(()=>JMA_AUTH?.getState().ready);
  const denied=await userPage.evaluate(async()=>{try{await JMA_CATALOG.create({id:'unauthorized-probe',category:'items',name_de:'Forbidden'});return false}catch(e){return e.message.includes('Rolle erforderlich')}});
  ok(denied,'Unauthorised user role is refused before catalog write');
  await userContext.close();await context.close();console.log('PASS catalog-storage checks:',checks);
 }finally{await browser.close();server.close()}
})().catch(error=>{console.error(error);server.close();process.exitCode=1});
