'use strict';
const assert=require('node:assert/strict'),http=require('node:http'),net=require('node:net'),crypto=require('node:crypto'),cp=require('node:child_process'),path=require('node:path');
const PORT=18787,TOKEN='test-token-123',SERVER=path.resolve(__dirname,'../bridge/server.js');let checks=0;const ok=(v,n)=>{assert.ok(v,n);checks++;console.log('PASS BRIDGE',checks,n)};
const child=cp.spawn(process.execPath,[SERVER],{env:{...process.env,JMA_BRIDGE_PORT:String(PORT),JMA_BRIDGE_TOKEN:TOKEN,JMA_BROWSER_ORIGINS:'http://127.0.0.1:5500'},stdio:['ignore','pipe','pipe']});
let output='';child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>output+=d);
const request=(method,path,body,token)=>new Promise((resolve,reject)=>{const data=body?JSON.stringify(body):'';const req=http.request({hostname:'127.0.0.1',port:PORT,path,method,headers:{...(data?{'content-type':'application/json','content-length':Buffer.byteLength(data)}:{}),...(token?{authorization:'Bearer '+token}:{})}},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>resolve({status:res.statusCode,body:s?JSON.parse(s):null}))});req.on('error',reject);if(data)req.write(data);req.end()});
function wsConnect(origin){return new Promise((resolve,reject)=>{const socket=net.createConnection(PORT,'127.0.0.1'),key=crypto.randomBytes(16).toString('base64');let buf=Buffer.alloc(0),ready=false;socket.on('connect',()=>socket.write(`GET / HTTP/1.1\r\nHost: 127.0.0.1:${PORT}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: ${key}\r\nOrigin: ${origin}\r\n\r\n`));socket.on('data',chunk=>{buf=Buffer.concat([buf,chunk]);if(!ready){const i=buf.indexOf('\r\n\r\n');if(i<0)return;const head=buf.subarray(0,i).toString();if(!head.includes('101 Switching Protocols'))return reject(Error(head));buf=buf.subarray(i+4);ready=true}if(ready&&buf.length>=2){let len=buf[1]&0x7f,off=2;if(len===126){if(buf.length<4)return;len=buf.readUInt16BE(2);off=4}if(buf.length<off+len)return;const msg=JSON.parse(buf.subarray(off,off+len).toString());resolve({socket,msg})}});socket.on('error',reject)})}
function maskedFrame(obj){const p=Buffer.from(JSON.stringify(obj)),mask=crypto.randomBytes(4),h=p.length<126?Buffer.from([0x81,0x80|p.length]):Buffer.from([0x81,0xfe,p.length>>8,p.length&255]),out=Buffer.alloc(p.length);for(let i=0;i<p.length;i++)out[i]=p[i]^mask[i%4];return Buffer.concat([h,mask,out])}
(async()=>{try{
 for(let i=0;i<50&&!output.includes('Browser WS');i++)await new Promise(r=>setTimeout(r,50));ok(output.includes('Position/heading provider: NOT AVAILABLE'),'Server starts with explicit pose limitation');
 let R=await request('GET','/health');ok(R.status===200&&R.body.positionAvailable===false&&R.body.provider===null,'Health exposes no fabricated pose/provider');
 R=await request('POST','/provider',{provider:'overwolf-gep',gameRunning:true,scene:'ingame'},null);ok(R.status===401,'Provider endpoint requires bearer token');
 R=await request('POST','/provider',{provider:'overwolf-gep',gameRunning:true,scene:'ingame',x:123,y:456,heading:90},TOKEN);ok(R.status===200&&R.body.poseAccepted===false,'Official GEP provider accepted while attempted pose fields are ignored');
 const ws=await wsConnect('http://127.0.0.1:5500');ok(ws.msg.data.connected&&ws.msg.data.gameRunning&&ws.msg.data.scene==='ingame','Browser receives real provider process/scene state');ok(ws.msg.data.x===null&&ws.msg.data.y===null&&ws.msg.data.heading===null&&ws.msg.data.accuracy==='unknown','Bridge never invents position/heading');
 const ts=Date.now();const pong=new Promise((resolve,reject)=>{let buf=Buffer.alloc(0);ws.socket.on('data',chunk=>{buf=Buffer.concat([buf,chunk]);if(buf.length<2)return;let len=buf[1]&0x7f,off=2;if(len===126){if(buf.length<4)return;len=buf.readUInt16BE(2);off=4}if(buf.length<off+len)return;try{const msg=JSON.parse(buf.subarray(off,off+len).toString());if(msg.type==='pong')resolve(msg)}catch{}});setTimeout(()=>reject(Error('pong timeout')),1000)});ws.socket.write(maskedFrame({version:1,type:'ping',timestamp:ts}));ok((await pong).timestamp===ts,'Browser JSON heartbeat receives matching pong');ws.socket.destroy();
 let denied='';await new Promise((resolve,reject)=>{const s=net.createConnection(PORT,'127.0.0.1'),key=crypto.randomBytes(16).toString('base64');s.on('connect',()=>s.write(`GET / HTTP/1.1\r\nHost: 127.0.0.1:${PORT}\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: ${key}\r\nOrigin: https://evil.example\r\n\r\n`));s.on('data',d=>denied+=d);s.on('end',resolve);s.on('error',reject)});ok(denied.includes('403 Forbidden'),'Unapproved browser Origin rejected');
 console.log(JSON.stringify({checks,real_game_pose:false,provider:'overwolf-gep-contract'}));
}finally{child.kill('SIGTERM')}})().catch(e=>{console.error(e);child.kill('SIGKILL');process.exitCode=1});
