const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results/control-orbit');fs.mkdirSync(out,{recursive:true});
const originalCss=cp.execFileSync('git',['show','checkpoint-before-control-orbit-20261001-6533300:settings-page.css'],{cwd:root,encoding:'utf8'}).replaceAll('route-live-map','route-map');
const fixture=fs.readFileSync(path.join(__dirname,'auth-fixture.js'),'utf8').replace("role:'user'","role:'owner'")+`\n(()=>{const f=supabase.createClient;supabase.createClient=(...a)=>{const c=f(...a),from=c.from.bind(c);c.from=t=>t!=='catalog_entries'?from(t):{select(){return this},order(){return this},range:async(a,b)=>({data:CATALOG_DATA.entries.slice(a,b+1).map(entry=>({id:entry.id,entry,revision:1})),error:null}),insert(){throw Error('Unexpected cloud write')},update(){throw Error('Unexpected cloud write')}};return c}})();`;
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\/$/,'/index.html'));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(error,bytes)=>{if(error)return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(bytes)})});
let checks=0;const ok=(value,label)=>{assert.ok(value,label);console.log('PASS',++checks,label)};
(async()=>{await new Promise(r=>server.listen(4183,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/tmp/once-human-chrome/opt/google/chrome/chrome',headless:true,args:['--no-sandbox']});try{
const context=await browser.newContext({viewport:{width:1920,height:1080},reducedMotion:'no-preference'});await context.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/javascript',body:fixture}));const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4183/#/home');await page.waitForFunction(()=>JMA_AUTH.getState().ready);await page.evaluate(()=>JMA_AUTH.signInWithPassword('preview@example.invalid','test-password'));const catalog=await page.evaluate(()=>JSON.stringify(CATALOG_DATA));
await page.evaluate(()=>location.hash='#/admin');await page.waitForSelector('.signal-orbit');await page.evaluate(()=>SETTINGS_PAGE.apply({...SETTINGS_PAGE.read(),smooth:false}));
const motion=()=>page.evaluate(()=>{const el=document.querySelector('.signal-orbit'),s=getComputedStyle(el),a=el.getAnimations()[0],timing=a?.effect.getTiming();return {name:s.animationName,duration:s.animationDuration,iterations:s.animationIterationCount,easing:s.animationTimingFunction,transform:s.transform,time:a?.currentTime,state:a?.playState,keyframes:a?.effect.getKeyframes().map(x=>x.transform),timing:timing?{duration:timing.duration,easing:timing.easing}:null}});
const before=await motion();await page.waitForFunction(t=>document.querySelector('.signal-orbit').getAnimations()[0]?.currentTime>t+300,before.time);const after=await motion();
ok(before.name==='admin-spin'&&before.duration==='12s'&&before.iterations==='infinite'&&before.easing==='linear'&&before.keyframes.includes('rotate(360deg)'),'Original 12-second linear rotation and keyframes restored with soft animations off');ok(after.state==='running'&&before.transform!==after.transform,'Actual transform advances over time');
await page.emulateMedia({reducedMotion:'reduce'});ok((await motion()).name==='none','Existing OS reduced-motion preference remains respected');await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>SETTINGS_PAGE.apply({...SETTINGS_PAGE.read(),smooth:true}));ok((await motion()).duration==='12s','Default motion unchanged');
const snapshot=()=>page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=r;img.onerror=r})));document.getAnimations().forEach(a=>{a.pause();a.currentTime=0});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return [...document.querySelectorAll('#app,#app *')].map(el=>{const style={};for(const pseudo of [null,'::before','::after']){const css=getComputedStyle(el,pseudo);style[pseudo||'self']=Object.fromEntries([...css].filter(k=>!(el.matches('.signal-orbit')&&['transform','animation-duration'].includes(k))).map(k=>[k,css.getPropertyValue(k)]))}const rect=el.getBoundingClientRect();return {tag:el.tagName,id:el.id,class:el.className,text:el.textContent,style,rect:[rect.x,rect.y,rect.width,rect.height].map(x=>Math.round(x*1000)/1000)}})});
const parity=[];
for(const route of ['admin','home','settings','profile','map']){
 await page.evaluate(route=>location.hash='#/'+route,route);await page.waitForFunction(route=>document.body.classList.contains('route-'+route),route);if(route==='admin'){await page.locator('[data-admin-view="overview"]').click();await page.waitForSelector('.signal-orbit')}
 for(const smooth of [true,false]){
  await page.evaluate(smooth=>SETTINGS_PAGE.apply({...SETTINGS_PAGE.read(),smooth}),smooth);const corrected=await snapshot();
  const sheet=page.locator('link[href*="settings-page.css"]');const href=await sheet.getAttribute('href');await context.route('**/settings-page.css*',r=>r.fulfill({contentType:'text/css',body:originalCss}));await sheet.evaluate((el,href)=>new Promise((resolve,reject)=>{el.onload=resolve;el.onerror=reject;el.href=href+'&orbit-baseline=1'}),href);await page.waitForFunction(()=>document.querySelector('link[href*="settings-page.css"]')?.sheet?.cssRules?.length>0);const baseline=await snapshot();
  assert.deepEqual(corrected,baseline,'Unexpected geometry/content/style change: '+route+' smooth='+smooth);parity.push({route,smooth,equal:true});ok(true,'Geometry, content and all other computed styles unchanged: '+route+' / smooth='+smooth);
  await context.unroute('**/settings-page.css*');await sheet.evaluate((el,href)=>new Promise((resolve,reject)=>{el.onload=resolve;el.onerror=reject;el.href=href+'&orbit-corrected=1'}),href);await page.waitForFunction(()=>document.querySelector('link[href*="settings-page.css"]')?.sheet?.cssRules?.length>0);
 }
}
await page.evaluate(()=>location.hash='#/admin');await page.waitForSelector('[data-admin-view="overview"]');await page.locator('[data-admin-view="overview"]').click();await page.evaluate(()=>SETTINGS_PAGE.apply({...SETTINGS_PAGE.read(),smooth:false}));await page.screenshot({path:path.join(out,'restored-overview-1920.png'),fullPage:true});await page.locator('[data-admin-view="editor"]').click();await page.waitForSelector('[data-editor-save]');ok(await page.locator('[data-editor-card]').count()===21&&await page.locator('[data-editor-filter]').count()===15,'Admin editor retains 21 entries and 14 category options');ok(await page.evaluate(c=>JSON.stringify(CATALOG_DATA)===c,catalog),'All original catalog values unchanged');ok(errors.length===0,'No JavaScript errors');fs.writeFileSync(path.join(out,'restored-results.json'),JSON.stringify({checks,before,after,parity,errors},null,2));console.log('PASS control-orbit checks:',checks);
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
