const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),cp=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results/map-flyby'),base=process.env.MAP_REGRESSION_BASE||'dfbe0a23c6f5d3a15f062b4e8d978f4dae688b97';fs.mkdirSync(out,{recursive:true});
const fixture=fs.readFileSync(path.join(__dirname,'auth-fixture.js'),'utf8').replace("role:'user'","role:'owner'")+`\n(()=>{const f=supabase.createClient;supabase.createClient=(...a)=>{const c=f(...a),from=c.from.bind(c);c.from=t=>t!=='catalog_entries'?from(t):{select(){return this},order(){return this},range:async(a,b)=>({data:CATALOG_DATA.entries.slice(a,b+1).map(entry=>({id:entry.id,entry,revision:1})),error:null})};return c}})();`;
const original={};for(const file of ['live-map.js','live-map.css'])original[file]=cp.execFileSync('git',['show',base+':'+file],{cwd:root,encoding:'utf8'});
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\/$/,'/index.html'));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();fs.readFile(file,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(b)})});
let checks=0;const results=[],errors=[];const ok=(c,label)=>{assert.ok(c,label);checks++;results.push(label);console.log('PASS',checks,label)};
(async()=>{await new Promise(r=>server.listen(4189,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'/tmp/once-human-chrome/opt/google/chrome/chrome',headless:true,args:['--no-sandbox']});try{
const make=async({width=1920,motion='no-preference',old=false}={})=>{const ctx=await browser.newContext({viewport:{width,height:width>820?1080:844},hasTouch:true,reducedMotion:motion});await ctx.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'text/javascript',body:fixture}));await ctx.route('https://*.supabase.co/**',r=>r.abort());if(old)for(const file of Object.keys(original))await ctx.route('**/'+file+'*',r=>r.fulfill({contentType:file.endsWith('.css')?'text/css':'text/javascript',body:original[file]}));await ctx.addInitScript(()=>{globalThis.__flyStarts=0;document.addEventListener('animationstart',e=>{if(e.animationName.startsWith('lm-flyby-depth'))__flyStarts++})});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4189');await page.waitForFunction(()=>JMA_AUTH.getState().ready);await page.evaluate(()=>JMA_AUTH.signInWithPassword('preview@example.invalid','test-password'));return {ctx,page}};
const go=async(p,route)=>{await p.evaluate(r=>location.hash='#/'+r,route);await p.waitForFunction(r=>location.hash==='#/'+r&&document.body.classList.contains('route-'+r),route)};
const waitFly=async p=>{await p.waitForSelector('.lm-flyby-creature',{state:'attached'});await p.waitForFunction(()=>document.querySelector('.lm-flyby-creature').getAnimations().length>0)};
const {ctx,page}=await make();await page.goto('http://127.0.0.1:4189/#/map');await waitFly(page);
ok(await page.locator('.lm-flyby').count()===1,'Direct authenticated map entry starts one layer');await page.waitForFunction(()=>__flyStarts===1);
await page.evaluate(()=>{globalThis.__flyNode=document.querySelector('.lm-flyby-creature');globalThis.__flyAnimation=__flyNode.getAnimations()[0];__flyAnimation.pause();__flyAnimation.currentTime=2300;globalThis.__flyStart=__flyAnimation.startTime});
await page.fill('#lmSearch','Silo');await page.waitForTimeout(250);await page.click('#lmResetFilters');await page.locator('[data-lm-cat]').first().click();await page.click('#lmZoomIn');await page.click('#lmZoomOut');await page.locator('[data-lm-marker]').first().click();await page.evaluate(()=>JMA_RENDER());
ok(await page.evaluate(()=>document.querySelector('.lm-flyby-creature')===__flyNode&&__flyNode.getAnimations()[0]===__flyAnimation&&__flyAnimation.currentTime===2300&&__flyStarts===1),'Search/filter/zoom/marker/re-render keep the same animation and timeline');
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(50);ok(await page.evaluate(()=>__flyNode.getAnimations()[0]===__flyAnimation&&__flyAnimation.currentTime===2300),'Resizing across mobile breakpoint keeps the same animation timeline');await page.setViewportSize({width:1920,height:1080});
ok(await page.evaluate(()=>{const l=document.querySelector('.lm-flyby'),i=l.querySelector('img');return getComputedStyle(l).pointerEvents==='none'&&getComputedStyle(i).pointerEvents==='none'&&i.complete&&i.naturalWidth===304}),'Decorative layer cannot intercept input; original image loads');
await page.click('#lmResetView');await page.locator('#lmBoard').scrollIntoViewIfNeeded();await page.waitForTimeout(50);
await page.waitForFunction(()=>{const b=document.querySelector('#lmBoard').getBoundingClientRect(),l=document.querySelector('.lm-flyby').getBoundingClientRect();return Math.abs(l.x-b.x-1)<1&&Math.abs(l.y-b.y-1)<1&&Math.abs(l.width-b.width+2)<1});ok(true,'Overlay follows settled board scrolling without changing map coordinates');
await page.evaluate(()=>{__flyAnimation.currentTime=6390;__flyAnimation.play()});await page.waitForSelector('.lm-flyby',{state:'detached'});await page.fill('#lmSearch','Silo');await page.waitForTimeout(250);ok(await page.locator('.lm-flyby').count()===0,'Completed intro disappears and search cannot replay it');
await go(page,'home');await page.locator('#mainNav [data-nav="map"]').click();await waitFly(page);ok(await page.locator('.lm-flyby').count()===1,'Home → header map starts a fresh single intro');await go(page,'home');await page.evaluate(()=>location.hash='#/live-map');await page.waitForFunction(()=>location.hash==='#/map');await waitFly(page);ok(await page.locator('.lm-flyby').count()===1,'Legacy alias redirects and starts exactly one canonical intro');
await page.reload();await waitFly(page);ok(await page.locator('.lm-flyby').count()===1,'Reload is a fresh visit');await page.emulateMedia({reducedMotion:'reduce'});await page.waitForSelector('.lm-flyby',{state:'detached'});await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>JMA_RENDER());ok(await page.locator('.lm-flyby').count()===0,'Enabling Reduced Motion cancels intro; disabling does not replay same visit');await ctx.close();
const dimensions=[];
for(const width of [1920,1280,768,390,360]){const a=await make({width}),b=await make({width,old:true});await go(a.page,'map');await go(b.page,'map');await waitFly(a.page);await a.page.locator('#lmBoard').scrollIntoViewIfNeeded();await b.page.locator('#lmBoard').scrollIntoViewIfNeeded();for(const p of [a.page,b.page])await p.evaluate(()=>document.fonts.ready);
const geometry=async p=>p.evaluate(()=>[...document.querySelectorAll('.lm-page,.lm-command-head,.lm-rail,.lm-toolbar,.lm-board,.lm-detail,.lm-navigator,.lm-butterfly')].map(el=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return [el.className,r.x,r.y,r.width,r.height,s.animationName,s.zIndex,s.transform]}));
// Existing animated creatures can be at different phases; compare their unchanged rules and boxes at an equal animation time.
for(const p of [a.page,b.page])await p.evaluate(()=>{for(const el of document.querySelectorAll('.lm-navigator img,.lm-butterfly'))for(const an of el.getAnimations()){an.pause();an.currentTime=0}});
assert.deepEqual(await geometry(a.page),await geometry(b.page));ok(true,'Original layout/creatures unchanged at '+width);
const samples=[];for(const [name,time] of [['far',1024],['approach',2816],['near',3712],['exit',5248]]){await a.page.evaluate(t=>{const an=document.querySelector('.lm-flyby-creature').getAnimations()[0];an.pause();an.currentTime=t},time);await a.page.waitForTimeout(50);samples.push(await a.page.evaluate(()=>{const el=document.querySelector('.lm-flyby-creature'),r=el.getBoundingClientRect();return {width:r.width,height:r.height,transform:getComputedStyle(el).transform,filter:getComputedStyle(el).filter}}));if(width===1920||width===390)await a.page.locator('#lmBoard').screenshot({path:path.join(out,width+'-'+name+'.png')});}
ok(samples[2].width>samples[0].width*2&&samples[2].width>samples[3].width*1.4&&samples.every(s=>s.transform.startsWith('matrix3d')),'Perspective/depth grows and recedes at '+width);
ok(await a.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&[...document.querySelectorAll('.lm-board img,.lm-flyby img')].every(i=>i.complete&&i.naturalWidth>0)),'No overflow or broken scene images at '+width);
const board=await a.page.locator('#lmBoard').boundingBox();ok(samples[2].width<board.width*.7,'Fly-by remains smaller than board at '+width);dimensions.push({width,samples});
await a.page.emulateMedia({reducedMotion:'reduce'});await go(a.page,'home');await go(a.page,'map');await a.page.waitForTimeout(80);ok(await a.page.locator('.lm-flyby').count()===0,'Reduced Motion suppresses entry at '+width);await a.ctx.close();await b.ctx.close();}
ok(errors.length===0,'No browser JavaScript errors');fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,results,dimensions,errors},null,2));console.log('PASS map-flyby checks:',checks);
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
