'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const ps=fs.readFileSync(path.join(root,'companion/windows-overlay/OnceHumanArchivOverlay.ps1'),'utf8');
const cs=fs.readFileSync(path.join(root,'companion/windows-overlay/OverlayNative.cs'),'utf8');
const cmd=fs.readFileSync(path.join(root,'companion/windows-overlay/start-overlay.cmd'),'utf8');
const readme=fs.readFileSync(path.join(root,'companion/windows-overlay/README.md'),'utf8');
const bridge=fs.readFileSync(path.join(root,'companion/bridge/server.js'),'utf8');
const map=fs.readFileSync(path.join(root,'live-map.js'),'utf8');
let checks=0;const ok=(v,n)=>{assert.ok(v,n);console.log('PASS WINDOWS OVERLAY',++checks,n)};
ok(ps.includes("$RepoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\\..'))"),'Overlay resolves repository root relative to its own folder');
ok(ps.includes('http://127.0.0.1:$WebPort/index.html')&&!ps.includes('https://'),'Website server stays local-only');
ok(ps.includes("--app=$mapUrl")&&ps.includes('OverlayEdgeProfile'),'Dedicated persistent Edge app profile');
ok(ps.includes('0x10')&&ps.includes('0x78')&&readme.includes('Shift+F9'),'Shift+F9 is the documented global toggle');
ok(ps.includes('[JmaOverlayNative]::TryGetClientBounds')&&cs.includes('GetClientRect')&&cs.includes('ClientToScreen'),'Overlay uses actual game client coordinates');
ok(cs.includes('SetProcessDpiAwarenessContext')&&cs.includes('EnablePerMonitorDpi'),'Per-monitor DPI awareness is enabled');
ok(cs.includes('SetWindowPos')&&cs.includes('HWND_TOPMOST'),'Overlay is positioned as topmost native window');
ok(cs.includes('SetForegroundWindow')&&ps.includes('FocusWindow($gameHwnd)'),'Hiding returns focus to the game');
ok(cs.includes('oncehuman')&&cs.includes('once_human')&&cs.includes('Once Human'),'Game detection has process and title fallbacks');
ok(cs.includes('excludedTitleProcess')&&cs.includes('processName.Contains("overwolf")')&&cs.includes('Archiv'),'Title fallback excludes browsers/Overwolf and prioritizes real process names');
ok(ps.includes("$OverlayWidthPercent = [Math]::Max(60")&&ps.includes("$OverlayHeightPercent = [Math]::Max(60"),'Overlay size inputs are bounded');
ok(ps.includes("Get-Command py")&&ps.includes("Get-Command python"),'Local website supports py/python launchers');
ok(ps.includes("Get-Command node")&&ps.includes('companion\\bridge\\server.js'),'Existing bridge starts automatically when Node is available');
ok(ps.includes("provider='windows-window'")&&bridge.includes("'windows-window'"),'Local window-status provider is wired to bridge');
ok(map.includes("'windows-overlay'")&&map.includes('URLSearchParams'),'Map auto-connect is opt-in to the private overlay query');
ok(cmd.includes('ExecutionPolicy Bypass')&&cmd.includes('OnceHumanArchivOverlay.ps1'),'One-click CMD launches only the local PowerShell overlay');
ok(readme.includes('keine echte Spieler-X/Y/Z-Position')&&readme.includes('kein Heading'),'README states the real-position limitation');
for(const banned of ['ReadProcessMemory','WriteProcessMemory','VirtualAllocEx','CreateRemoteThread','SetWindowsHookEx','DLL-Injection'])ok(!ps.includes(banned)&&!cs.includes(banned),'No memory/injection primitive: '+banned);
console.log(JSON.stringify({checks,windows_runtime_tested:false,real_position:false,overwolf_required:false}));
